### ISSUE TITLE
Use Reactive Extensions to manage items fed from server

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1017]
Implement in Toggl source the code improvements developed during the test week.

**Comment by alfonsogarciacaro** [comment]
I've replaced TPL DataFlow package with Reactive Extensions (Rx).

For the moment there are no more changes. At the end, I didn't touch `MessageBus` but created a middleman instead (`EventDispatcher`) to translate `MessageBus` subscriptions to .NET events which Rx can consume.

A bit more abstraction is probably needed, as right now there are many things that should be disposed manually: `MessageBus` and Rx subscriptions.

Hopefully, the Rx chain makes it easier to add async operations later. An interesting addition right now is a buffer that will hold messages coming to fast.

**Comment by alfonsogarciacaro** [comment]
This work is done in alfonso-reactive branch

**Comment by monday8am** [comment]
ahmm.. ok. :)
