### ISSUE TITLE
Drawer to follow material design guidelines on android.

### ISSUE THREAD

**Issue by taavirehemagi** [toggl/mobile#1024]
- [ ] add edicated area for user avatar and name
- [ ] align username and avatar to left
- [ ] use white background instead of arrows under list (?)

![patterns_navdrawer_scrolling1](https://cloud.githubusercontent.com/assets/2154171/11273568/a5317322-8edc-11e5-9e0a-8b4eda027122.png)

current 
<img width="461" alt="screen shot 2015-11-19 at 16 43 54" src="https://cloud.githubusercontent.com/assets/2154171/11273634/01daddd4-8edd-11e5-8597-f9e834f12e09.png">

**Comment by monday8am** [comment]
out of date. new design implemented.
