### ISSUE TITLE
Fix issues with Diff algorithm in alfonso-reactive branch 

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1029]
The replaced items are not being correctly detected and this causes the items not be in order when the list is updated.

**Comment by monday8am** [comment]
@alfonsogarciacaro please, refer the part of code that closes this issue.

**Comment by alfonsogarciacaro** [comment]
Closed by commit [5990da6](https://github.com/toggl/mobile/commit/5990da6810f066e7147d40f1afb4e795c85dfbd2)
