### ISSUE TITLE
Use asynchronous tests

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1054]
Many tests use a custom made function named `RunAsync`. This shouldn't be need as NUnit support `async` tests, so remove it.

**Comment by alfonsogarciacaro** [comment]
[This is implemented](https://github.com/toggl/mobile/compare/alfonso-tests-async). However, it has been necessary to upgrade to NUnit 3, which apparently is not supported yet by Xamarin Studio. We'll wait until Xamarin supports the new version of NUnit to merge the PR.

**Comment by monday8am** [comment]
closed by #1371
