### ISSUE TITLE
Confusing buttons in Client Select Dialog

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1057]
In version 8.0.8 there are now two buttons in the Client Select Dialog reading "New client" and "Create". This is confusing for the users: "Create" should actually read "Ok"

<img width="410" alt="screen shot 2015-12-02 at 08 56 19" src="https://cloud.githubusercontent.com/assets/8275461/11527984/59d7f402-98e4-11e5-9560-7f4a6ed62c98.png">

**Comment by monday8am** [comment]
for me, we need a couple of things here:
- Manage the case that there are not clients (show a label saying "No clients")
- Replace the "Create" by "Cancel" .. but in this case, I think maybe "Cancel" is not needed. 
@alfonsogarciacaro  @taavirehemagi

**Comment by monday8am** [comment]
closed by: https://github.com/toggl/mobile/pull/1061
