### ISSUE TITLE
Unexpected behaviour when touching "Last sync XX minutes ago"

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1058]
In version 8.0.8 the syncing is not done anymore in the drawer. However, when you click the message "Last sync XX minutes ago" the touch somehow gets through the drawer and a Time Entry Edit Screen gets displayed.

**Comment by monday8am** [comment]
Not only in version 8.0.8. The entry item that is just behind this label is touched and the Edit screen is opened. We should avoid that collecting the touch events in the navigator (or finding a more elegant solution)

**Comment by monday8am** [comment]
@alfonsogarciacaro this bug was fixed?

**Comment by alfonsogarciacaro** [comment]
I have a quick and dirty solution [in this branch](https://github.com/toggl/mobile/compare/alfonso-issue-1058) but I wasn't sure if I should send the PR.

**Comment by monday8am** [comment]
send the PR (one step forward)
