### ISSUE TITLE
OBM experiment M83 - iOS Timer page empty view

### ISSUE THREAD

**Issue by melissasepp** [toggl/mobile#1062]
* To go live "sometime in the middle of January" - ETA to be confirmed
* Display text “Welcome! Start your timer here” with an arrow pointing towards the green "Start" icon on the timer page upon signup until the user has created his first time entry.
* Display it to all users who have signed up from mobile and who are in "experiment_group = included" group.
* When the user starts his first time entry from the green "Start" button, track it as experiment_actions = "click"

Mockup:
![screen shot 2015-12-03 at 14 16 10](https://cloud.githubusercontent.com/assets/15194147/11560345/7bfaa248-99c8-11e5-9988-1be9ccada9f6.png)

**Comment by monday8am** [comment]
closed by https://github.com/toggl/mobile/pull/1164
