### ISSUE TITLE
Entry (Login) screen redesign.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1067]
In order to implement the no-user mode, we need to add a new button to invite users to enter to our app without login.

Besides, we need to decide the importance of this button, if the login form should appear, which option is more important for us and maybe create an experiment with it.

@pe0ny @melissasepp We'll need your smart criteria and good taste to define these tasks :)

**Comment by pe0ny** [comment]
First screen:
![toggl android - first screen](https://cloud.githubusercontent.com/assets/5064445/12638188/ebabbb52-c5a3-11e5-9537-a5ad8b03b4a4.png)

Log in:
![toggl android - log in](https://cloud.githubusercontent.com/assets/5064445/12638199/f47e4790-c5a3-11e5-955d-8aa2008bc6c0.png)

Sign up:
![toggl android - sign up](https://cloud.githubusercontent.com/assets/5064445/12638207/ffc17618-c5a3-11e5-9e9e-bf083e866ae7.png)

Check Zeplin for additional info and assets.

**Comment by monday8am** [comment]
@pe0ny for me is perfect. @taavirehemagi

**Comment by monday8am** [comment]
design defined and uploaded to Zeplin.
