### ISSUE TITLE
Evaluate the use of ModernHttpClient and Refit libs.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1083]
These libraries could improve our existing TogglRestClient

https://github.com/paulcbetts/ModernHttpClient
https://github.com/paulcbetts/refit

**Comment by alfonsogarciacaro** [comment]
After having a look at both libraries, it seems their purpose is different:
- `ModernHttpClient` provides **performance** by using native Http libraries for Android/iOS instead the Mono implementation. The good thing is it uses the same interfaces as `System.Net.Http` so apparently no change is needed besides the instantiation of the `HttpClient`. However, before implementing it, it would be better to make some benchmarks to confirm there's a noticeable performance improvement.
- `Refit`, on the other hand, seems to be mostly a matter of **convenience** by automatically implementing a REST API model with generic properties by using attributes (similar to what `sqlite-net` does). It's not that difficult to make something similar with `HttpClient` and `Newtonsoft.Json`. For now, I think we need to simplify the JSON import process, by separating the JSON parsing and DB persistence processes, and then consider whether to use `Refit` or not.

**Comment by monday8am** [comment]
ok ok. *ModernHttpClient* will be in our recent plans then. Thanks for your answer @alfonsogarciacaro
