### ISSUE TITLE
Android app fails to sync

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/mobile#1089]
TogglJoey 8.0.9
Android version 4.4.2
Samsung Galaxy S-4 mini GT-l9195 (my personal phone)

**Comment by monday8am** [comment]
Not enough description.

**Comment by taavirehemagi** [comment]
It's repeatable on küllike's phone (and other older phones I think). Will investigate.

**Comment by monday8am** [comment]
it is working correctly. Checked with @kyllikekimmel
