### ISSUE TITLE
Write post about the Reactive and Diff implementation

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1109]
Write a post to be published in Toggl blog explaining why and how we have refactored the code to use Reactive Extensions and the Diff algorithm to update the time entries' collection.

This post should also be the base for an entry in the project Wiki.

**Comment by alfonsogarciacaro** [comment]
[Post is written](https://github.com/toggl/mobile/wiki/Toggl-goes-Reactive%21) but we still need to decide some edits.

**Comment by monday8am** [comment]
:+1:  @alfonsogarciacaro close it then and open a new issue related with "modify article..."
