### ISSUE TITLE
Improve placeholder text for "Project" and "Description" in Edit screen

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/mobile#1127]
* Instead of "Project" as a placeholder: 
If a user hasn't added a project, display "Add project" if a user has at least one existing project, and "Create project" if they don't. 

* If a user hasn't added a description, display "What are you doing?" instead of "Description". 

Talking about these fields: 
![android_edit](https://cloud.githubusercontent.com/assets/8287467/12016512/749758d0-ad54-11e5-92a2-411802d18972.png)

**Comment by monday8am** [comment]
:+1: 
@kyllikekimmel could you give us a suggestion for the next screen? (when you create a new project)

**Comment by kyllikekimmel** [comment]
There should be an empty view there with an image of a little Toggler - do you want to change it?

**Comment by monday8am** [comment]
ein? :D ... maybe my explanation was short. I refer to the screen that appears when you try to add a new project. You press: Select Project and go to a list, and then press the (+) button at bottom and go to another screen: New Project Screen.

**Comment by kyllikekimmel** [comment]
You mean this one?
![image](https://cloud.githubusercontent.com/assets/8287467/12039157/a69a0e0a-ae66-11e5-9aa2-992a1433f23e.png)

**Comment by monday8am** [comment]
yes!

**Comment by kyllikekimmel** [comment]
How about keeping it simple? 
* Project -> Project name
* Client -> Client name

**Comment by monday8am** [comment]
closed by https://github.com/toggl/mobile/pull/1145
