### ISSUE TITLE
Build a prototype for unidirectional architecture

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1131]
Build a prototype following the architecture detailed in [this document](https://github.com/toggl/mobile/blob/master/Docs/unidirectional_architecture.md) to help the team decide if refactor the whole app in this direction.

**Comment by monday8am** [comment]
@alfonsogarciacaro this issue is related with a task that can't be accomplished in 1 day. Please, create small chunks related with it. I'll close it for the moment.
