### ISSUE TITLE
Dialogs are crashing because ViewModel isn't created.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1139]

**Comment by alfonsogarciacaro** [comment]
It shouldn't be a problem to use `async` methods in `OnViewCreated` and such (James Montagno has an example [here](https://github.com/jamesmontemagno/Xamarin.Android-AppCompat/blob/master/AppCompat/AppCompat/ViewPagerFragment.cs#L89)) but we need to be careful the ViewModel isn't accessed ahead of time by other creation events.

[This PR](https://github.com/toggl/mobile/pull/1146) attempts to fix the issue for `EditTimeEntryFragment` buy using a generic `AwaitPredicate` method (it checks regularly if a condition has been fulfilled and completes the task when it is). If we take this approach, we should do a similar thing for other potentially problematic Android activities.

**Comment by monday8am** [comment]
fixed by https://github.com/toggl/mobile/commit/94e5d642680d319da382044c64674c404e01c9f5
