### ISSUE TITLE
When adding a project to an entry group without it a new time entry is created

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1144]
A new time entry shouldn't be created, instead all time entries in the group should be edited.
Add test for this.

**Comment by monday8am** [comment]
![image](https://cloud.githubusercontent.com/assets/1842773/12144935/4823dc9a-b48b-11e5-962f-5c4b329fd61a.png)

seems to be a modification over a group trigger an *Add* and not an *Update*
