### ISSUE TITLE
Sony Smartwatch 3: Wear App does not start-up

### ISSUE THREAD

**Issue by stv0g** [toggl/mobile#1149]
Toggl entry on wearable appears. But when starting the app, it immediately returns to the Wear home screen.

Watch: Sony Smartwatch 3
Version: 8.1.0

**Comment by dekov** [comment]
I can confirm that.

App version: 8.1.1

**Comment by irwineffect** [comment]
Issue is also present on LG Watch R.

App version 8.1.1

**Comment by taavirehemagi** [comment]
This should be fixed in the new release. 8.1.2 Can you check?

**Comment by dekov** [comment]
Working fine in Sony SmartWatch 3,
Thank you!

**Comment by irwineffect** [comment]
Works now on the LG Watch R too. Thanks!

**Comment by monday8am** [comment]
closed by release 8.1.2
