### ISSUE TITLE
OBM experiment M90 - Android empty view with mock entries

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/mobile#1150]
Experiment ID: 90

Create Timer page empty view with mock time entries. Something along the lines of this: 
![android_exp_2](https://cloud.githubusercontent.com/assets/8287467/12144002/77c561b0-b48d-11e5-86e9-6de1c53e3e35.png)

The text and arrow remain the same as in the 1st Android experiment. 

Image for the mock time entries: 
![mock_entries_android](https://cloud.githubusercontent.com/assets/8287467/12144033/a4583f54-b48d-11e5-8043-d06a54d80902.png)

**Comment by monday8am** [comment]
thanks @kyllikekimmel

**Comment by pe0ny** [comment]
mdpi:
![obm-mock-entries-mdpi](https://cloud.githubusercontent.com/assets/5064445/12392551/a3beed94-bdf8-11e5-8d7c-c04891ce742f.png)

hdpi:
![obm-mock-entries-hdpi](https://cloud.githubusercontent.com/assets/5064445/12393276/597721ac-bdfd-11e5-991e-4be82dde41f7.png)

xhdpi:
![obm-mock-entries-xhdpi](https://cloud.githubusercontent.com/assets/5064445/12393284/614c6504-bdfd-11e5-8669-1bbd0eb160d0.png)

**Comment by monday8am** [comment]
closed by #1186
