### ISSUE TITLE
Subject is destroyed before unsubscribe from Message bus in TimeEntriesFeed.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1157]
https://github.com/toggl/mobile/blob/master/Phoebe/Data/Utils/TimeEntriesFeed.cs#L51

under some condition, the subject doesn’t exist and a message is received, maybe because you destroy the subject first, before unsubscribe the message bus.

https://github.com/toggl/mobile/blob/master/Phoebe/Data/Utils/TimeEntriesFeed.cs#L59

Raygun report https://app.raygun.io/crashreporting/gn9q04/errors/1032500139 has more details about the error

**Comment by alfonsogarciacaro** [comment]
The `Dispose` method should cancel the subscription to `MessageBus` before disposing the `Subject`. [This PR](https://github.com/toggl/mobile/pull/1158) fixes that.
