### ISSUE TITLE
NullReferenceException: Don´t nullify collection in LogTimeEntriesViewModel.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1160]
Raygun report https://app.raygun.io/crashreporting/gn9q04/errors/1025051809 has more details about the error

**Comment by alfonsogarciacaro** [comment]
I couldn't find any place where `RecyclerCollectionDataAdapter.CollectionData` is set to null, but probably this has to do with Android view cleanup. To be sure, I've protected the references to `CollectionData` using the null-conditional operator, but in the constructor (there's something else wrong if we're passing a null `collectionData` to the constructor anyway).

**Comment by monday8am** [comment]
https://github.com/toggl/mobile/blob/master/Phoebe/Data/ViewModels/LogTimeEntriesViewModel.cs#L85
here is nullified.

**Comment by monday8am** [comment]
fixed at https://github.com/toggl/mobile/commit/eccde1501975e6748c042003d96993cda2d0014f
