### ISSUE TITLE
[Android] Crash on login

### ISSUE THREAD

**Issue by rulrok** [toggl/mobile#1190]
I have a 4.2.2 Android phone Samsung Galaxy Pocket 2.
Whenever I try to log in, the application simply crashes without any clue of why.

I have tried creating another account with another email just to test and see if the problem was solely the google authentication process, but the app still crashes the same way.

That's really bugging me since I have to totally rely on my desktop computer to track everything.
I used to have a Moto X with Android 5.1 running without any problem but I no longer have it.

Thanks

**Comment by monday8am** [comment]
hi @rulrok , thanks for your feedback. I'll send you a private message!
