### ISSUE TITLE
Description change gets reverted when editing an entry

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1220]
How to reproduce:
- Select an entry and enter edit screen
- Edit the description
- Now select either the start and stop time and change it, touch DONE
- When the timer picker is dismissed, notice the description has gone back to its previous state

**Comment by monday8am** [comment]
Check if the bug appears when a *new* time entry is added.

**Comment by kyllikekimmel** [comment]
Steps to reproduce on a new time entry: 
* No-user mode, Grouped entries selected
* Start a timer, add a description and an existing project
* Tap Back arrow
* Time entry looks as it should with the description and project attached 
* When that entry is stopped (from the Stop button), the project and description disappear, leaving the entry with (no project) and (no description).
