### ISSUE TITLE
Change the default duration for manual time entries to 00:00:00

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/mobile#1228]
At the moment it's 5 minutes for some reason, ending 1 minute in the future.

**Comment by monday8am** [comment]
@kyllikekimmel  the reason is to notify the user that this entry should be modified. In theory, we should have a predefined values in order to save time to the user. 00:00:00 doesn't help in this approach.

**Comment by monday8am** [comment]
closed at #1604
