### ISSUE TITLE
Copy updates for no-user mode

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/mobile#1235]
- [x] Feedback page "no access" copy: 
"Oh no! You don't have access yet. Sign up to get in touch with us!"
- [x] Sign up page copy: 
"You'll get access to reports and many other benefits" 
(Place above the e-mail field with @pe0ny's permission?)
- [x] Reports page "no access" copy: 
"Boost your productivity! Sign up to get access to your reports."
- [x] Confirmation screen copy: 

"Congrats! You're now signed up. With your new account you can: 
- See your time in reports 
- Track together with your team
- Analyze your data in depth in Toggl web"

**Comment by taavirehemagi** [comment]
Outdated
