### ISSUE TITLE
Remove the Checkmark button from manual mode screen

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/mobile#1238]
Since neither the new time entry nor the existing entry edit screens don't have the Checkmark button, manual time entry screen shouldn't either - all three screens are pretty much the same. 

If a user is used to tapping the Back button to save the changes (which is how it works on both new entry edit screen and existing entry edit screen), they would expect that this is how you also save a manual time entry.

**Comment by monday8am** [comment]
but you're removing the possibility of *Cancel* ... he can delete it later of course..

**Comment by kyllikekimmel** [comment]
They can use the back button of their phone for this, and yes, delete the entry later. It works the same way for the other screens (new TE and existing TE edit screens), so I don't see a problem. 

Also: It would make sense that if the user doesn't make any changes, no time entry will be added. This means the user will have to make at least one change - add a duration or description or project, anything, in order for the time entry to be saved.

**Comment by monday8am** [comment]
ok ok, then we have to remove the check button from New Project page too.

**Comment by kyllikekimmel** [comment]
Do we, though? "Create project" page is pretty different from all the "Edit TE" screens in my opinion.

**Comment by monday8am** [comment]
let's talk about behaviours and try to reproduce it for each items in the same way. The 3 basic ops. are: _add new_ - _delete_ - _modify_. We will apply this operations to many items (not only time entries) like projects, clients, etc.

We have two options:
- Save and close in the same action using the Back button. Don't save if not changes are made. Don't bring the cancel option explicitly.
- Define a button for Save action and let the Back button only for cancel the op.

"Create project" is a different screen of "Edit TE" but when you add a manual TE, they are the same: an screen to create a new item.

**Comment by kyllikekimmel** [comment]
I guess that makes sense. Will you add an option to delete projects from the mobile app soon? The thing is, right now it's not easy to delete accidentally added projects easily - you'll need to go to web app for that. But I do see what you mean. For me it wouldn't be an issue if Create Project screen also operated the same way, without the Checkmark button. I know @taavirehemagi had objections, though.
