### ISSUE TITLE
Wrong typecast disposing TimeEntryCollection<T> in Android. 

### ISSUE THREAD

**Issue by taavirehemagi** [toggl/mobile#1248]
E/AndroidRuntime( 3691): FATAL EXCEPTION: main
E/AndroidRuntime( 3691): Process: com.toggl.timer, PID: 3691
E/AndroidRuntime( 3691): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 3691): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime( 3691): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3691): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 3691): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3691): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3691): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime( 3691): 	... 2 more
E/AndroidRuntime( 3691): Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.InvalidCastException: Specified cast is not valid.
E/AndroidRuntime( 3691):   at Toggl.Phoebe.Data.ViewModels.LogTimeEntriesViewModel.DisposeCollection () <0x6e201828 + 0x00064> in <filename unknown>:0 
E/AndroidRuntime( 3691):   at Toggl.Phoebe.Data.ViewModels.LogTimeEntriesViewModel.Dispose () <0x6d051220 + 0x00197> in <filename unknown>:0 
E/AndroidRuntime( 3691):   at Toggl.Joey.UI.Fragments.LogTimeEntriesListFragment.OnDestroyView () <0x6d04f030 + 0x0008f> in <filename unknown>:0 
E/AndroidRuntime( 3691):   at Android.Support.V4.App.Fragment.n_OnDestroyView (IntPtr jnienv, IntPtr native__this) <0x6d04b9a0 + 0x00037> in <filename unknown>:0 
E/AndroidRuntime( 3691):   at (wrapper dynamic-method) System.Object:c3ad453a-8f68-44fd-af06-421576335ccd (intptr,intptr)
E/AndroidRuntime( 3691): --- End of stack trace from previous location where exception was thrown ---
E/AndroidRuntime( 3691):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x6d055798 + 0x00024> in <filename unknown>:0 
E/AndroidRuntime( 3691):   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod) <0x6ad51e98 + 0x000db> in <filename unknown>:0 
E/AndroidRuntime( 3691):   at Android.App.Activity.OnDestroy () <0x6b248210 + 0x00103> in <filename unknown>:0 
E/AndroidRuntime( 3691):   at Toggl.Joey.UI.Activities.BaseActivity.OnDestroy () <0x6b2480e0 + 0x0000f> in <filename unknown>:0 
E/AndroidRuntime( 3691):   at Android.App.Activity.n_OnDestroy (IntPtr jnienv, IntPtr native__this) <0x6b248090 + 0x00037> in <filename unknown>:0 
E/AndroidRuntime( 3691):   at (wrapper dynamic-method) System.Object:df385b1e-ca0e-4632-b74d-6029af3499cf (intptr,intptr)
E/AndroidRuntime( 3691): 	at md5d0def3047409cb8594a2ecbf8acf6aee.BaseActivity.n_onDestroy(Native Method)
E/AndroidRuntime( 3691): 	at md5d0def3047409cb8594a2ecbf8acf6aee.BaseActivity.onDestroy(BaseActivity.java:46)
E/AndroidRuntime( 3691): 	at android.app.Activity.performDestroy(Activity.java:5630)
E/AndroidRuntime( 3691): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1123)
E/AndroidRuntime( 3691): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3799)
E/AndroidRuntime( 3691): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3830)
E/AndroidRuntime( 3691): 	at android.app.ActivityThread.access$1500(ActivityThread.java:174)
E/AndroidRuntime( 3691): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
E/AndroidRuntime( 3691): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3691): 	at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime( 3691): 	at android.app.ActivityThread.main(ActivityThread.java:5593)
E/AndroidRuntime( 3691): 	... 5 more
W/ActivityManager(  870):   Force finishing activity com.toggl.timer/md5d0def3047409cb8594a2ecbf8acf6aee.LoginActivity

refers to this line I think https://github.com/toggl/mobile/blob/master/Phoebe/Data/ViewModels/LogTimeEntriesViewModel.cs#L85

**Comment by monday8am** [comment]
@taavirehemagi is a typecast problem. Seems to be it will crash in any phone, not in older phones only.

**Comment by monday8am** [comment]
typecast is working correctly.
