### ISSUE TITLE
Feedback: I started a timer, then edited...

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1253]
[TestFairy session: 24](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2767366/sessions/24#t=16m53s) 
Description: I started a timer, then edited the start time of the running timer. the new duration was displayed on the running entry on Timer screen byt not in the header - this still showed the time since I actually pressed Start. once I reopened the app, the issue was gone, though.
App: Toggl Time Tracker - 8.1.1 (65) #3
Date: 2016-02-11 01:04:53
User: kyllike.kimmel@gmail.com
Device: Samsung - Galaxy S4 mini

**Comment by taavirehemagi** [comment]
Fixed in https://github.com/toggl/mobile/commit/e65d12443001836042ede8277301a58cfe9eb144
