### ISSUE TITLE
The running timer is not alway displayed in the top bar.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1254]
[TestFairy session: 24](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2767366/sessions/24#t=20m15s) 
Description: the running timer is not always displayed in the top bar
App: Toggl Time Tracker - 8.1.1 (65) #3
Date: 2016-02-11 01:06:21
User: kyllike.kimmel@gmail.com
Device: Samsung - Galaxy S4 mini

**Comment by monday8am** [comment]
@taavirehemagi @kyllikekimmel  this bug doesn't happen in the current released version. My idea it was introduce with the no-user-code. That's why I added the tag.

**Comment by taavirehemagi** [comment]
This is fixed in https://github.com/toggl/mobile/commit/e65d12443001836042ede8277301a58cfe9eb144
