### ISSUE TITLE
Feedback: manually added time entry disappeared after press Save.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1256]
[TestFairy session: 24](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2767366/sessions/24#t=24m21s) 
Description: manually added time entry disappeared
App: Toggl Time Tracker - 8.1.1 (65) #3
Date: 2016-02-11 01:10:18
User: kyllike.kimmel@gmail.com
Device: Samsung - Galaxy S4 mini

**Comment by monday8am** [comment]
@kyllikekimmel how you detected that the time entry disappeared?
You tried to create it, pressed "Save" and it didn't appear in the list?

**Comment by taavirehemagi** [comment]
Fixed in latest no-user mode version
