### ISSUE TITLE
Feedback: Issue this morning - sync failed,  time entries gone. Restart solved.

### ISSUE THREAD

**Issue by chipbite** [toggl/mobile#1261]
Hi, consider this feedback/observation!
I experienced some strange behavior this morning:I time my commute vs worktime. 

At one point it says sync failed (low cell coverage at this point) and then display is inconsistent:
![image](https://cloud.githubusercontent.com/assets/559199/13000732/47668538-d15e-11e5-9548-e70455c4fbee.png)

So I check the website - and on the website the entries are actually all there, as they should:
![image](https://cloud.githubusercontent.com/assets/559199/13000739/5feebe18-d15e-11e5-9c3f-7594a761a0ba.png)

Anyway, a restart of the android client solved it and all entries reappeared. Which was very good, since otherwise I would have been sad. :-)

Again observation, FWIW - don't know if this is helpful.
BR! /marcus

**Comment by alfonsogarciacaro** [comment]
Hi Marcus! Thanks for all the detailed information, this is very helpful indeed :) We're currently working to fix the syncing problems and we'll also investigate this particular case and give you a response as soon as possible. Cheers!

**Comment by alfonsogarciacaro** [comment]
It seems this is caused because the views haven't been correctly refreshed after a syncing fail, but the good thing is the data was kept intact so everything worked fine when restarting the app.

We're working now in a major architectural change to simplify (and hopefully improve) the syncing and view refreshing, which should fix this kind of problems. We'll inform you when the new version is ready so you can check if the problem is solved. Keeping the issue open until then.

Thanks a lot and have a nice weekend!

**Comment by chipbite** [comment]
Sounds good!

It's a great app, and I appreciate the challenges you face, especially multi-device entry over short time periods: This morning I did not switch device until coming to the office and moving to my PC, but during the day - between work at station and roving between different meetings, I do quite a bit of switching between logging timeentries from my PC (especially the PC client idle check is great when people grab you for a chat) and then logging entries from my phone (to lunch, meeting, chat, then back at station). 
So it is really useful/vital to me that the clients manage to be in sync. (Cell coverage at the office is not always stellar, that certainly does not help... )

Thanks, and a nice weekend to you aswell Sir! :-)

**Comment by chipbite** [comment]
Short update, this situation (as in the Screenshots above) happened once more in the afternoon/evening.

**Comment by monday8am** [comment]
out of date. Hopefully closed with unidirectional branch (v8.1.6)
