### ISSUE TITLE
Integrate RxChain with Android screens

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1270]
Test the RxChain (see #1222) with one or several Android screens.

**Comment by monday8am** [comment]
@alfonsogarciacaro it is an small resume of the _state_ needed and the changes to the _state_ made by wach ViewModel:

Operations by ViewModels.

`LogTimeEntriesViewModel`
*State required:*
- TimeEntryData running.
- Is Loading data (bool, scroll bottom loader)
- Is Refreshing data (bool, scroll top loader)
- Loading operation has errors.
- TimeEntryData list (events)
- IsGroupedMode (bool)

*Operations over state:*
- Put TimeEntryData (start/stop/continue)
- Delete TimeEntryData (delete)
- Request sync.
- Request load more.

`EditTimeEntryViewModel`
*State required:*
- TimeEntryData list. (to get selected TimeEntryData)
- Tag list (separated table?)

*Operations over state.*
- Put TimeEntryData (save)
- Save TagList related with edited TimeEntryData (separated table?)
- Delete TimeEntryData.

`ProjectListViewModel`
*State required:*
- ProjectData list.
- WorkspaceData list.
- ClientData list.
- TaskData list.

*Operations over state.*
- Nothing.

`NewProjectViewModel`
*State required:*
- ProjectData list. (to check for existing names)

*Operations over state:*
- Put ProjectData.
- Put ProjectUserData.

`NewClientViewModel`
*State required:*
- ClientData list. (to check for existing names)

*Operations over state:*
- Put ClientData.

`TagListViewModel`
*State required:*
- TagData List

*Operations over state:*
- Nothing.

`NewTagListViewModel`
*State required:*
- TagData List (to check existing names)

*Operations over state:*
- Put TagData.

**Comment by alfonsogarciacaro** [comment]
Reducers for operations over state have been implemented. Other issues will be opened to deal with each ViewModel separately.
