### ISSUE TITLE
Switch out empty view to an onboarding overlay

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/mobile#1295]
When a user enters "no-user mode" for the first time, display this overlay: 
![image](https://cloud.githubusercontent.com/assets/8287467/13141628/0219cb92-d641-11e5-8ab1-41ff69bf1e85.png)
(Remove the three buttons at the bottom and the option to skip + also the three dots at the end of the sentence, please.)
 
The overlay should only be displayed once for each new user. One the user closes the overlay by tapping the CTA button, take them to Timer screen.

**Comment by taavirehemagi** [comment]
Closed in 2171a46
