### ISSUE TITLE
6 number max. to represent more than 24h time (with seconds)

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1296]
If I start the timer and then edit the start time to be in the past, the timer shows different durations in the top bar and the time entry itself. The time entry shows duration from the moment I actually pressed the Start button but the header shows the time I edited it to show.

App: Toggl Timer - 7.0.24 (21)
TestFairy session: [46](https://toggl.testfairy.com/projects/2175323-toggltimer/builds/2790091/sessions/46#t=03m41s)
Date: 2016-02-17 12:16:29
User: User-28
Device: Apple - iPhone 5c (iPhone5,4) - 9.2.1 API 1

**Comment by monday8am** [comment]
@kyllikekimmel here we have another kind of problem. The times are correct, the only difference is how they are shown with 6 numbers. You created a time entry with more than 24h. The original time is: 30:00:00:03 (and seconds running). 

One label shows: 00:00:03
Other labels show: 30:00:00

we could check the web and see how they do it... or show 8 digits.

**Comment by kyllikekimmel** [comment]
8 digits is too long since it doesn't fit into the top bar. The web shows times over 24 hours in 6 digits: 
![screen shot 2016-02-18 at 14 51 37](https://cloud.githubusercontent.com/assets/8287467/13143794/ff94c7a6-d64e-11e5-92a3-7545ceabd328.png)
It would make sense to display it the same way.

**Comment by monday8am** [comment]
maybe I'm confused, in any case is good to know your opinion. Thanks!

**Comment by kyllikekimmel** [comment]
Confused about what? 
In any case, what do all these numbers refer to in this format: 30:00:00:03? 
first 2 are hours, next two minutes, then 2 seconds... but what about the last ones?

**Comment by monday8am** [comment]
it is what I mean, the bug is not related with the +24h and 6 digits. Is a bad UI representation, some part of the code does well, the other part not.

**Comment by kyllikekimmel** [comment]
Hm, alright.
