### ISSUE TITLE
Add obm info to the UserAgent in HTTP requests

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1300]
`?i:-obm-%d` (where the %d is the experiment number the app supports/waits) should be appended to the user-agent header [here](https://github.com/toggl/mobile/blob/master/Phoebe/Net/TogglRestClient.cs#L44).

Example: the user-agent should be like `TogglRoss 7.XX.XX-obm-103`
Note: multi-experiment support is scheduled to be supported in iteration 2 of obmv3

**Comment by monday8am** [comment]
closed by 7f49fa6fdab9d82c046043f5d2e7ed53357542a3
