### ISSUE TITLE
Check if the user is requesting entries older than 2 months

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1301]
If the user hasn't been syncing for 2 months, the server will refuse sync attempts later with the following message: `Bad Request:The 'since' value should be within last two months`

Before syncing, the app should check if entries older than 2 months are being requested and in that case discard current data and refetch `api/v8/me?with_related_data=true`

Alternative solution: use api/reports/v2/* endpoints

**Comment by monday8am** [comment]
out of date. Fixed in unidirectional implementation (v8.1.6 Android, v7.1.6.1 iOS)
