### ISSUE TITLE
Google login throws a NetworkError on first try.

### ISSUE THREAD

**Issue by taavirehemagi** [toggl/mobile#1327]
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable
[AuthManager] Failed authenticate user.
[AuthManager] md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.Threading.Tasks.TaskCanceledException: A task was canceled.
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0002d] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:193 
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:372 
[AuthManager]   at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x004af] in /Users/builder/data/lanes/2692/e98e9627/source/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs:382 
[AuthManager] --- End of stack trace from previous location where exception was thrown ---
[AuthManager]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00027] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:190 
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
[AuthManager]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:580 
[AuthManager]   at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext () [0x000a9] in /Users/builder/data/lanes/2692/e98e9627/source/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:274 
[AuthManager] --- End of stack trace from previous location where exception was thrown ---
[AuthManager]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00027] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:190 
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
[AuthManager]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
[AuthManager]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwai

**Comment by taavirehemagi** [comment]
Correction, not a NetworkErrror, but a task is canceled.

**Comment by taavirehemagi** [comment]
For some reason it fails while doing SendAsync sometimes. 
https://github.com/toggl/mobile/blob/master/Phoebe/Net/TogglRestClient.cs#L724

**Comment by monday8am** [comment]
@refiito Margus, the answer from server is clear:
 `Toggl.Phoebe._Net.UnsuccessfulRequestException: 502 (Bad Gateway) `
when we try to auth using a `googleAccessToken` . On the other hand, if we try with `username` and `pass` it works ok.

Have you an idea of why it happens?

**Comment by refiito** [comment]
Where could I see the response body?

the 502 response is returned for 2 possible reasons:
 1. API panics and "disappears" (the body will have the response from nginx in it then)
 2. Google returns an error (possible errors, that are handled that way are: "OAuthError: updateToken" - error with the requested token; TLS and TCP timeouts and some generic error, when Google just responds with "Error from Google"), then we respond with 502, since, well, we cannot fix google :)

also, FIY:
for Google login one must provide a HTTP auth header in the format of:
user: the actual access token
password: google_access_token

**Comment by monday8am** [comment]
We are using the correct format (I guess) passing the same format as email/pass but with token/google_access_token as you describe. Google handshake finishes ok, because we get the token id properly. The 502 comes after call the API, so, I vote for the first option.

have you a way, using curl, to send google token? 
`curl -u xxx: google_access_token http://toggl.space` ?

**Comment by refiito** [comment]
yes, you can use curl for testing (indeed just `curl -u <token>:google_access_token https....`)

**Comment by monday8am** [comment]
Google network issue. Without solution from our side.
