### ISSUE TITLE
iOS improvements related with revision of 7.0.21

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1330]
- [ ] Reports gives error to a new user - I hope only because this is staging mode?
- [ ] If I edit the Stop time and make it before start time (start at 23:50 and stop at 23:00), we should display a warning. This can easily happen by accident with the 'wheel of madness'.
- [ ] Either log isn't working or it is taking a loooong time. Either way we should notify the user - a spinner (or even grey out the 'sign in' button so it isnt clickable) for when it's logging you in and an error message for when you put in sth wrong. 
- [ ] Why so many different amounts in the middle of the pie chart? I see two amounts in eur and one in usd for the chosen period in reports. It looks crowded.
- [ ] Two parts of the pie chart in reports are the same color - if possible it would be better to use different colors, otherwise I cant see the different parts visually

**Comment by monday8am** [comment]
@kyllikekimmel About that:
_Why so many different amounts in the middle of the pie chart? I see two amounts in eur and one in usd for the chosen period in reports. It looks crowded._ 
because we have limited colours for projects. The colour used correspond to the colour of the project. Two projects with the same colour will look like that.

**Comment by kyllikekimmel** [comment]
Ok, I understand about the colors, but this doesn't explain why we show the total amount tracked in two different sums.

**Comment by amulware** [comment]
Closing this because it is very much out of date. If any of the issues above remain/crop up again, we can create individual issues for them.
