### ISSUE TITLE
Android Wear: App does not start up on Zen Watch 2

### ISSUE THREAD

**Issue by mileschen360** [toggl/mobile#1334]

**Comment by monday8am** [comment]
@mileschen360 thanks for your feedback. We'll release a new version this week with this bug hopefully fixed.

**Comment by monday8am** [comment]
@mileschen360 could you test if the new version is working correctly?

**Comment by mileschen360** [comment]
It works now. Thanks!

**Comment by monday8am** [comment]
nice to know. We'll update a bit the wear app in the next releases. Thanks again.

**Comment by mileschen360** [comment]
It broke again after recent update.

**Comment by stevedoesthings** [comment]
I am experiencing the same issue, also zenwatch 2.
