### ISSUE TITLE
Empty month in yearly report

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1372]
A user (Android) has reported that when displaying yearly reports, the month of September looks empty. This doesn't happen in the web.

The other months are fine. Also there's no problem in weekly and monthly reports. It seems there's a problem with the interpretation of the JSON coming from the server. The issue must be investigated.

Desk case (with screenshots):
https://toggl.desk.com/agent/case/259963#

**Comment by monday8am** [comment]
apparently closed by #1501
