### ISSUE TITLE
Create script to insert secret API keys into cs config file

### ISSUE THREAD

**Issue by amulware** [toggl/mobile#1381]

**Comment by monday8am** [comment]
@amulware I added some tags and colours :P

**Comment by amulware** [comment]
Some more details would be appreciated too. I.e. what key has to be inserted where exactly.

**Comment by monday8am** [comment]
from https://github.com/toggl/mobile/blob/master/Phoebe/Build.cs
just replace the empty spaces in
`public static readonly string GcmSenderId = ""` with tokens that you can replace later (parsing with an script) ..is an idea, if you have a better idea you're welcome.
