### ISSUE TITLE
Use the Project billable value to set TimeEntryData billable value.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1410]
When a time entry is started and the user attaches a billable project to it, the TE be marked as ‘billable’ automatically.

@kadrihvl

**Comment by kadrihvl** [comment]
Another user reported this as it's causing issues with his work flow. I'll add the case no here so we'll be able to notify him when this is fixed. #272492

**Comment by monday8am** [comment]
:+1:

**Comment by monday8am** [comment]
fixed in iOS.

**Comment by monday8am** [comment]
Android is already using the new version of "backend code", so, it will be fixed in Android too.
