### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by roosmaa** [toggl/mobile#145]
Implement websocket support for Phoebe. This will allow the data to be kept up to date when the user is using the app.

**Comment by monday8am** [comment]
not needed at this moment (IMO). Websockets could be implemented to give us a better real time feeling (a real "real time" feeling :)). But it goes in the opposite way to a silent syncing behaviour and offline mode.

If you have something to comment:@taavirehemagi @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
I agree that keeping a connection open all the time may be too much for our app and have an impact on battery life. Also, as you said, actually we need to focus now on allowing the user to work with no connection at all with the server from the very beginning.

**Comment by monday8am** [comment]
discarded.
