### ISSUE TITLE
OBM UI fixes.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1465]
1. make the text less transparent - right now it isn’t really visible
2. move the text a little bit more up
3. take away “you can” and leave just “Start your timer here”
4. point the arrow from the word Welcome to the Start button (make it less straight)

![image](https://cloud.githubusercontent.com/assets/1842773/14426692/f1abb890-fff0-11e5-96a4-7b4bedb145de.png)

@melissasepp

**Comment by monday8am** [comment]
Solution:

![screen shot 2016-04-12 at 19 55 54](https://cloud.githubusercontent.com/assets/1842773/14488368/3d31241c-0168-11e6-866b-56b0bd806f99.png)

closed by #1474

**Comment by melissasepp** [comment]
@monday8am Can you also make the arrow more round like in the mockup (https://cloud.githubusercontent.com/assets/15194147/11560345/7bfaa248-99c8-11e5-9988-1be9ccada9f6.png)?
