### ISSUE TITLE
App crash on login (Android 4.1.2)

### ISSUE THREAD

**Issue by RobDesideri** [toggl/mobile#1490]
After last update I can't login  both via email and Google method. In no-user mode, app go right.

**Comment by alfonsogarciacaro** [comment]
Hi there! Would you mind giving the beta version a try? If you reproduce the error with the beta version we can receive information that would be very helpful to fix it. You can download the beta from [here](https://tsfr.io/xrkvaq). Thanks a lot for your help!

**Comment by RobDesideri** [comment]
@alfonsogarciacaro ok, I do. Hope this can help you. I am already several days that I can not use the app.

**Comment by DjouLi** [comment]
Same thing here. Toggl crashes on Android 4.2.2 when login in. No-user mode OK. Beta app downloaded. Login in does not work either. Hope this will help!

**Comment by monday8am** [comment]
Hi @DjouLi @RobDesideri, we have detected one of the bugs correctly, thanks a lot for your collaboration. We'll start to investigate today and we'll release a new beta version for you to test as soon as possible (in the next two days).

**Comment by alfonsogarciacaro** [comment]
Hello @DjouLi @RobDesideri, we have uploaded a new beta version with a fix for the problem. Could you please give it a try and confirm if it works for you now? Thanks a lot for you help!
https://tsfr.io/xrkvaq

**Comment by DjouLi** [comment]
@alfonsogarciacaro It works! Fantastic. Thanks to you and @monday8am for your reactivity.

**Comment by alfonsogarciacaro** [comment]
Thanks to you and @RobDesideri for all your help! We'll be releasing the fix in the Google Store shortly, you can use the beta version until then if you need it :)

**Comment by RobDesideri** [comment]
@alfonsogarciacaro Tanks! Now _login_ go right, but _app itself_ sometime crash (2 crash in 1 minute). 
I keep beta app so you can receive feedback.

**Comment by alfonsogarciacaro** [comment]
This is really helpful, thanks! Checking the errors right now...

**Comment by monday8am** [comment]
many bugs will be fixed with 8.1.6 version. closed until new feedback.
