### ISSUE TITLE
Error when creating MainDrawerActivity in v8.1.3

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1491]
Related to #1490 

There seems to be an error when creating `MainDrawerActivity` in v8.1.3. Users' feedback in TestFairy shows the following error:
```Java.Lang.RuntimeException: Cannot add header view to list -- setAdapter has already been called.```

The last method from our codebase in the Stack trace is: `Toggl.Joey.UI.Activities.MainDrawerActivity.OnCreateActivity`

See the following report in TestFairy for more info:
https://free.testfairy.com/projects/1985413-toggltimetracker/builds/3231392/sessions/24

**Comment by monday8am** [comment]
XI info:
https://insights.xamarin.com/app/Toggl-Android/issues/3946

**Comment by alfonsogarciacaro** [comment]
Following the error reports and considering the bug doesn't appear in Offline mode, seems the problem is in [these lines](https://github.com/toggl/mobile/blob/master/Joey/UI/Activities/MainDrawerActivity.cs#L115-L117). However, it doesn't affect al users.

**Comment by monday8am** [comment]
considering XI info, it only affets 4.0.2, 4.1, 4.2 Android version users.

**Comment by alfonsogarciacaro** [comment]
[This commit](https://github.com/toggl/mobile/commit/a2f05288b5fcb8dbca36f42ad865dc177bb2c873) contains a tentative fix. It just moves the addition of the HeaderView before setting the adapter as it was before [this commit](https://github.com/toggl/mobile/commit/b07a63b1f665324e778a6a802947302f000e21e8).

I couldn't reproduce the bug in my phone so I'll send a beta version to the affected users to check if the bug is fixed before sending the PR.

**Comment by monday8am** [comment]
👍

**Comment by alfonsogarciacaro** [comment]
Closed by PR #1492.
