### ISSUE TITLE
Add Migration Screen with progress indicator

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1504]
Performing the migration transparently during the startup may freeze the app for several seconds causing the OS to kill. Start the app normally and add the migration check afterwards so I progress indicator can be shown if needed.

**Comment by alfonsogarciacaro** [comment]
New migration logic implemented in [this PR](https://github.com/toggl/mobile/pull/1507). Screen pending.

**Comment by amulware** [comment]
And unfinished screen is waiting for @monday8am's feedback on branch `ios-migration-view`. ;)

**Comment by monday8am** [comment]
closed by #1525
