### ISSUE TITLE
Android Widget Improvements

### ISSUE THREAD

**Issue by kennyklee** [toggl/mobile#1511]
Phone: Nexus 5x

Not exactly sure if these are bugs or missing features, but there is a lot left to be desired for the Android widget.

1) Does not sync with the rest of the ecosystem.  For example, if I start/stop timers from my Mac or Chrome extension, the widget is not updated.

2) When the widget is expanded vertically and displaying the list of tasks, there is a play (start timer) button next to each task.  When I click on the start time button for one of the tasks (with description/project), it does not resume timer for that task.  It creates a new timer without description or project.

3) You cannot group the tasks for the widget.  There is a setting for the Android app (which works), but the grouping configuration does not apply to the widget. 

4) Often, when I go from the widget to the actual Android app, the app crashes.

Hope this helps.  I love toggl, but with these bugs fixed, I would log it even more.

**Comment by vedr4n** [comment]
We're getting more reports of bad experiences with the widget. See Desk case #332323 for details. 

User reported the widget crashing as well.

**Comment by amulware** [comment]
The upcoming update should hopefully improve this. The issue can be reopened if these problems remain after.
