### ISSUE TITLE
Continuation action in messages is not triggered in all cases.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1524]
Continuation action in messages is triggered from `SyncManager`. If the reducer doesn't trigger a server request, the cycle isn't completed. Maybe we should try to figure out a solution based on Rx. It is needed only for tests for the moment.

**Comment by alfonsogarciacaro** [comment]
We can run the `LocalOnly` continuations after the reducers have been executed:
https://github.com/toggl/mobile/blob/unidirectional/Phoebe/Reactive/StoreManager.cs#L72

**Comment by monday8am** [comment]
closed by #1529
