### ISSUE TITLE
Update App Store profile (SEO reasons)

### ISSUE THREAD

**Issue by annikatoggl** [toggl/mobile#1527]
New app title: Toggl Work Time Tracker

New description:
Leading timesheet app for tracking work hours. Use the timer to log task times and get reports based on the time usage. All the time logs are synced to the cloud and you can track time also in the web version, desktop app and with a Chrome extension - all your data is safely under one account. 

New pics: (1st reports pic and 2nd timer page pic - main benefit should be visible right away, the login screen picture doesn't add any value)

![toggl ios 002 timer](https://cloud.githubusercontent.com/assets/7711888/15037667/d5619be2-12a5-11e6-961a-d00b8ca89e97.png)
![toggl ios 004 projects](https://cloud.githubusercontent.com/assets/7711888/15037666/d55e843e-12a5-11e6-9d83-c3f04240dd55.png)

**Comment by monday8am** [comment]
@annikatoggl you mean remove all previous description and use the new? 
About the name, maybe 4 words is too much.. the name appears under the icon and usually has one single word or two in special cases:

![image](https://cloud.githubusercontent.com/assets/1842773/15079163/ded29598-1384-11e6-9ff2-49f9d14cf1ca.png)

if we use "Toggl Work Time Tracker" you'll see "Toggl Work..." . 
We can do like Prince ("The Artist Formerly Known as Prince" -> "TAFKAP")

**Comment by annikatoggl** [comment]
@monday8am I think it's possible to use shorter name under the icon (just Toggl) and then the longer name appears on the App Store. 

http://stackoverflow.com/questions/11817190/how-to-have-a-long-name-for-the-app-store-and-then-a-short-name-under-the-icon
