### ISSUE TITLE
Toggl Logo is deformed at startup (Android)

### ISSUE THREAD

**Issue by HansCronau** [toggl/mobile#1545]
Toggl logo seems "squashed" on startup. (Circle is not perfectly round.)
Version Toggl: unknown (latest from Google Play)
Devlice: LG G3
Android: 5.1.1

![screenshot_2016-05-13-11-11-21](https://cloud.githubusercontent.com/assets/977860/15244234/6ae7381a-1900-11e6-8996-0a925210d643.png)

**Comment by monday8am** [comment]
@HansCronau thanks for your feedback! We'll fix it soon.

**Comment by monday8am** [comment]
closed at 886157e37296d711d608996d44935fd5c1b2a715
