### ISSUE TITLE
Project list ordering by client first in iOS

### ISSUE THREAD

**Issue by roosmaa** [toggl/mobile#158]
Should consider implement a client based project sorting. Either as the only option or as an alternative to the current one.

**Comment by whatSocks** [comment]
It would be nice to have projects ordered by "most frequent" as well.

**Comment by monday8am** [comment]
hi @whatSocks, I'll create a separated issue for that. thanks for your suggestion!

**Comment by monday8am** [comment]
closed by https://github.com/toggl/mobile/pull/1242
