### ISSUE TITLE
iOS onboarding experiment is not displayed properly

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/mobile#1589]
It seems that the design is displayed slightly to the right. Screenshots taken on iPhone 5c.

The arrow is missing in the "included" group view: 
![image](https://cloud.githubusercontent.com/assets/8287467/15465742/d840edd0-20de-11e6-8e30-fa2570cfde39.png)

The "excluded" group view (default view) also seems to be displayed slightly to the right: 
![image](https://cloud.githubusercontent.com/assets/8287467/15465756/ead33ff2-20de-11e6-928c-18ab63c9f3a0.png)

**Comment by kyllikekimmel** [comment]
Please let me know when it's fixed so I can test it both before and right after it's released!

**Comment by kyllikekimmel** [comment]
Looks the same on iPhone 6 as well.

**Comment by monday8am** [comment]
@amulware could you add a link to the solution?

**Comment by amulware** [comment]
#1618
