### ISSUE TITLE
iOS 7.1.0: Automatic edition of stop time causes an error

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1593]
A user is complaining about a design choice when editing the start and stop times of an entry.

> If I quickly start and stop an event and then seek to adjust times (to do when I need to add an entry or break an old one into two) I used to adjust the start time and then input the time spent. Now it immediately moves end time so if I go too far back and then move forward in time I get an error that start time must be before end time and i have not found a way round this.

Case 290576

A possible solution could to be no to push the stop time further than the current time.

**Comment by alfonsogarciacaro** [comment]
Another comment about the same issue:

> the start/end time validation. Under certain circumstances the app opens a popup saying the times are invalid. For example if you set the end time before the start time, it will pop up letting you know that&#39;s not valid. This makes adjusting times very annoying because you naturally could scroll the time wheel to an earlier hour before being able to adjust the minutes. If you don&#39;t want to revert your changes on this one, at least make the validation text appear in a non-modal format - perhaps a red banner at the top or bottom that disappears when the fields are valid. This way the user can get into an intermediary invalid state and not have to constantly be tapping the OK button on the way to the desired time value.

https://toggl.desk.com/agent/case/290782

**Comment by alfonsogarciacaro** [comment]
Another comment about this:

> I frequently find myself fighting the logic for the clock dials when I have to enter a back dated time entry.
> I think it could be improved by seeing how the HoursKeeper app does it.
> Basically, disable logic checks until both dials are set at what the user has selected - THEN perform the logic checks on what they have entered.
> Don&#39;t auto correct the user while they&#39;re selecting something that seems weird to the logic, but is intentional. It seems weird to the logic for that moment prior to the user adjusting the other dial, too.

Case 292971

**Comment by monday8am** [comment]
we can move the Start-Stop time check to the `Save` operation maybe. The user changes everything and we show the alert when he try to save the edited entry.

**Comment by alfonsogarciacaro** [comment]
Fixed by PR #1629
