### ISSUE TITLE
iOS 7.1.0: "Sliding Drawer" gesture conflicting with "Continue Entry" swipe

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1594]
A user mentioned that many times he tried to continue an entry (by swiping it to the right) the sliding drawer was open instead. He's suggesting to disable the gesture or making the recognition area smaller. The issue can't be reproduced in the simulator

> the sliding drawer that reveals the settings by sliding from the left. Disable this or reduce the gesture recognition area greatly. When modifying start/end times and swiping up &amp; down, the drawer keeps trying to reveal the settings menu. If the settings menu was something I used very often, this might be understandable but I&#39;ve opened the setting only two or three times in the thousands of times I&#39;ve opened and used the app. This is not a useful feature, I can tap the top left icon to reveal the settings if I need to; I don&#39;t need it accessible from any point on the screen.

Case 290782

**Comment by amulware** [comment]
Funny. I sometimes have the opposite problem. I try to open the drawer and instead continue an entry. We may have to rethink this?

**Comment by alfonsogarciacaro** [comment]
Disabling the gesture to open the drawer will solve both issues because then the user is always forced to use the hamburger button to open the drawer.

**Comment by amulware** [comment]
I tend to agree. In general, if I understand correctly, the same gesture (at least when started at the left edge of the screen) is associated with going back (in our case, popping a view controller from the navigation stack), which makes more sense on non-timer screens, where there would also be no conflict with the continue gesture.

**Comment by pe0ny** [comment]
I agree with Alfonso. Let's disable the sliding gesture to open the drawer. So, to open the drawer users have to tap on the burger icon only.

**Comment by alfonsogarciacaro** [comment]
Fixed by PR #1624
