### ISSUE TITLE
iOS 7.1.0: Adding entries manually

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1598]
It's not possible to manually add a new entry in v7.1.0. This feature must be brought back.

Some users also requested that it's possible to set the start day when adding the entry (this also affects entry edition).

**Comment by amulware** [comment]
Code goes here (currently empty event handler):
https://github.com/toggl/mobile/blob/master/Ross/ViewControllers/LogViewController.cs#L152

**Comment by amulware** [comment]
resolved with https://github.com/toggl/mobile/pull/1604
