### ISSUE TITLE
Cannot change start time past end time

### ISSUE THREAD

**Issue by amulware** [toggl/mobile#1601]
Trying to set the start time in the future of the end time will cause the app to show an error message that this wasn't allowed.

So I change the end time to be in the future of the new start time, then change the start time again, which then changes the end time, causing the time I wanted to move the time entry to be added to the duration.

**Comment by alfonsogarciacaro** [comment]
This seems to be related to #1593

**Comment by monday8am** [comment]
let´s move the discussion to #1593
