### ISSUE TITLE
Tapping on Time entry reveals hidden "Continue" text

### ISSUE THREAD

**Issue by taavirehemagi** [toggl/mobile#1625]
<img width="330" alt="screen shot 2016-05-30 at 15 18 17" src="https://cloud.githubusercontent.com/assets/2154171/15649427/290fb3a4-267a-11e6-8abf-30fdf6e152f2.png">

**Comment by amulware** [comment]
Fixed with 9c63adf61715d0d28b8954650fca0de6c0b40a3a
