### ISSUE TITLE
TE keeps running after tapping Stop button

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobile#1626]
Time entry (not timer on top) keeps running after tapping stop button. Green start button appears.

Flow:
1) Start new TE (tapping start button)
2) Tap "Add project"
3) Select project
4) Going back to the list view
5) Stop TE

https://free.testfairy.com/projects/2175323-toggltimer/builds/3528570/sessions/57

**Comment by alfonsogarciacaro** [comment]
On hold. We haven't been able to confirm the bug yet.

**Comment by amulware** [comment]
Pretty sure this cannot happen anymore. Closing until it occurs again.
