### ISSUE TITLE
Toggl crashes when selecting it on Android Wear

### ISSUE THREAD

**Issue by Mumumurilo** [toggl/mobile#1631]
The Toggl icon appears on my watch, but when I try to open it it returns a message saying that Toggl has crashed.

I have never been able to run the app in my watch.

**Comment by floe** [comment]
Same for me, also Moto 360 (v2).

**Comment by fonorobert** [comment]
another user reports the same issue with a Nexus 5 on Android 6.0.1
desk case: 299496

**Comment by salimalim123** [comment]
Hello, it doesn't work with the Sony Smartwatch 3 either.

**Comment by salimalim123** [comment]
My version is 8.1.5 by the way.

**Comment by alex-fgsfds** [comment]
Same for me on Sone SM3 as well. Crash upon launch. Version 8.1.5. Device build M1D63X, Android Wear 1.5.0.3269884.

**Comment by webADDIE** [comment]
Same with Asus ZenWatch 2 632C Build M1D64L Android Wear 1.5.0.3365647

**Comment by kschach** [comment]
Same with Huawei Watch.

**Comment by moritzrupp** [comment]
Toggl also crashes on the Polar M600 smartwatch (using the Play store version, 8.1.5). Android Wear version 1.5.0.3594574, Google Play services 10.0.84 and Android OS 6.0.1.
Once I open Toogl on my smartwatch it directly crashes.

The current beta version doesn't crash, but freezes on the loading screen.

**Comment by Trevortds** [comment]
Same with Zenwatch 3. The wear app seems to simply not work at all for anybody. Has development on it stopped?

**Comment by jonasem** [comment]
Same on Zenwatch 3, Android Wear 1.5.0.357

**Comment by sergeyotro** [comment]
Moto 360 2gen, the same issue, instant crash on start.

**Comment by alex-fgsfds** [comment]
I think we can safely come to a conclusion that Wear app doesn't work at all and change the issue title accordingly.

**Comment by Trevortds** [comment]
@alex-fgsfds This is correct. I got an email from their support saying as much, all development of the wear app has stopped since May 2016.

**Comment by Mumumurilo** [comment]
@Trevortds Oh well. That's sad. I'll close the thread then.

**Comment by moritzrupp** [comment]
Too bad as this was one reason for me to try toggl at all.

**Comment by fonorobert** [comment]
Robert here from the Toggl support team.
Our apologies for not responding here sooner.

The Wear app is on hold for now as our priority is to update the core apps instead. While we hope to get back to the Wear app at some point, I'm afraid that's a bit down the road.

**Comment by Fenntasy** [comment]
Can you really affirm it is on your plans or did you judge it not important because of too few users?
