### ISSUE TITLE
iOS 7.1.6: Missing tags when using autocomplete

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1639]
Related to #1597

When using the autocomplete function, the description and the project are correctly carried over to the new entry. However this is not the case for the tags, which still must be manually added.

**Comment by alfonsogarciacaro** [comment]
Apparently, this is the same behaviour as in the web and desktop clients: autocomplete doesn't carry tags over. So please feel free to close the issue if this is indeed working as intended.

**Comment by monday8am** [comment]
no user feedback related with that. closed for the moment.
