### ISSUE TITLE
Time entry durations changing to hundreds of hours

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1640]
Seems to be a format / calculation problem. 

![image](https://cloud.githubusercontent.com/assets/1842773/15772872/0294d81a-2974-11e6-84c2-62aba41a5b48.png)

**Comment by fonorobert** [comment]
logs for a related case in desk case 295566

**Comment by amulware** [comment]
Please note that the sum in the header is just fine. The problem here is that all the time entries are hundreds of hours long.

**Comment by amulware** [comment]
May be fixed. Needs testing.

**Comment by monday8am** [comment]
hopefully closed by #1662 
marked as pending for further check.
