### ISSUE TITLE
Create new loading splash screen and animation

### ISSUE THREAD

**Issue by amulware** [toggl/mobile#1653]
Splash screen will be solid white/light gray with the toggl logo and text on it (slightly larger than the one on the timer page).

![toggl ios - splash 1x](https://cloud.githubusercontent.com/assets/3987892/15884454/e5c640a8-2d50-11e6-9d81-79495f1f4d9a.png)

When loading finishes, the background will fade away, while the logo will move and scale (smoothly, i.e. animated) to the top of the timer list.

Create on new branch, branching off of `paul-ios-new-timer-screen`. This branch already includes the new design which has the logo at the top of the timer list, serving as end point for the animation

**Comment by pe0ny** [comment]
Assets are available in Zeplin ;)
