### ISSUE TITLE
iOS 7.1.0: App freezes when adding new project

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobile#1654]
App freezes (actually projects list freezes) when trying to add new project:
![photo](https://cloud.githubusercontent.com/assets/5064445/15886859/dbd60a12-2d67-11e6-87ac-37def1f1a534.PNG)

I can go back to TE edit view and TE list (navigation works) but content view is frozen. Only thing I can see is projects list.

Flow:
1) Created new time (tapped Start button)
2) Tapped "Add project"
3) Tapped "+"
4) Added project name
5) Tapped "add client"
6) Tapped "+"
7) Added client name
8 ) Tapped "add" on client screen
9) Tapped "add" on project screen

Only way to get out from this thing was to close the app completely.
It happens all the time when I try to create a new project.

**Comment by amulware** [comment]
closed by #1674
