### ISSUE TITLE
[BUG] [Android] Miscalculation on report bar

### ISSUE THREAD

**Issue by waltermelow** [toggl/mobile#1657]
First, congratulations for your great project.
I find a bug miscalculation on report bar, using Adroid app.

Attach app screenshot, web view screenshot and CVS data export time entries.

<img alt="app-screenshot" src="https://cloud.githubusercontent.com/assets/196580/15918084/3df71b5a-2e03-11e6-9a6c-96395942caed.jpg" width="50%" height="50%"></img>

<img alt="web-screenshot" src="https://cloud.githubusercontent.com/assets/196580/15918088/4adc86de-2e03-11e6-9fa3-2ae1e0ab9a88.png" width="50%" height="50%"></img>

[Toggl_time_entries_2016-05-30_to_2016-06-05.csv.txt](https://github.com/toggl/mobile/files/306073/Toggl_time_entries_2016-05-30_to_2016-06-05.csv.txt)

**Comment by monday8am** [comment]
fixed at:
https://github.com/toggl/mobile/blob/unidirectional/Phoebe/Data/Json/JsonMapper.cs#L328
https://github.com/toggl/mobile/issues/1657
