### ISSUE TITLE
Start iOS OBM experiment M83 from scratch

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobile#1710]
Since iOS design changed we'll start OBM experiment #1062 from scratch.
Design and assets are available in Zeplin.

* Go live when #1282 is ready
* Display text “Welcome! Start your timer here” with an arrow pointing towards the green "Start" icon on the timer page until the user has created his/her first time entry.
* If user has seen the experiment, created time entries and deletes all time entries, don’t show the experiment anymore.
* If user switches to manual mode, keep the experiment visible. 
* Display it to all users who have signed up from mobile and who are in "experiment_group = included" group.
* When the user starts his/her first time entry from the green ​*”Start"*​ button, track it as ​*experiment_actions = “startbutton”*​ (add those actions to both included and excluded groups to compare afterwards)
* When the user starts his/her first time entry from the ​*”Add"*​ button in manual mode, track it as ​*experiment_actions = “addbutton”*​ (add those actions to both included and excluded groups to compare afterwards)

Melissa or Küllike will test the experiment before we go live!

![toggl ios - obm ver2](https://cloud.githubusercontent.com/assets/5064445/16443322/ce6a09e4-3de0-11e6-83c1-57b99f1eee4a.png)

**Comment by kyllikekimmel** [comment]
Experiment number should be 116, not 83.
