### ISSUE TITLE
[GAT-TGI001-3] Tapping on '+' icon in the 'Tags' screen, crashes the app 

### ISSUE THREAD

**Issue by gatgithub** [toggl/mobile#1881]
_Issue No_: 3
_Device_: iPhone 5S, iOS 10 Gm
### Affected Component(s)
- Timer

---
### Bug Description

ACTUAL RESULTS:-
Tapping on '+' icon in the 'Tags' screen, crashes the app

EXPECTED RESULTS:-
App should not crash

OTHER NOTES / ERROR MESSAGES:-
- Username: test.account.2@toggl.com
- Password: password: 123
- Repro: 5/5
- Video: http://bugs8.gatserver.com/uploads/8351e4cd8d09d2cb569ead61316829d9.mp4
- Crash Log: http://bugs8.gatserver.com/uploads/07d6bc4004971ab98c9fa0f3ffe28f3b.crash

---
### Reproduction Steps
- launch the app and login
- Tap on the green icon at the bottom of the screen
- Select 'Mobile'
- Tap '+' button in the opened 'Tags' screen

**Comment by willsb** [comment]
I can't reproduce this on any iOS device. Tested on simulator and devices running both iOS 9.X and 10.X
