### ISSUE TITLE
Keyboard disappears when trying to create a time entry

### ISSUE THREAD

**Issue by kadrihvl** [toggl/mobile#1935]
TogglRoss/7.2.2

> Whenever I am filling in details relating to my time, the app continually jumps back to the previous screen, which is very annoying and slows the process down. I am using an iPhone 6s Plus on iOS 10.0.2. I uninstalled and then re-installed the app. I have now been testing for over a week but the problem still occurs. While entering the details of what I was working on, the keyboard will randomly disappear.
> Logs in case #360036

**Comment by kadrihvl** [comment]
Similar case with logs: #365619

**Comment by nicktoggl** [comment]
Similar case at case/382499 logs included
