### ISSUE TITLE
iOS app crashes when new signup adds project

### ISSUE THREAD

**Issue by fonorobert** [toggl/mobile#1967]
Steps to repro:
- download Toggl app
- sign up for new accnt in iOS app
- start a timer, go to assign a project
- tap "+" to add new project, app crashes

removing and reinstalling the app fixes it

**Comment by nicktoggl** [comment]
It looks like it could also be an issue for all installations made in 2017 even when using old accounts and first time app use.

**Comment by nicktoggl** [comment]
Additionally when trying to get feedback reports, users have reported this message comes up "Sending failed: Could not send your feedback.  Please try again".
