### ISSUE TITLE
Blocky, broken display after flick-scroll

### ISSUE THREAD

**Issue by MarcinGil** [toggl/mobile#278]
From time to time, after I do a quick flick-scroll this happens:

![screenshot_2014-07-28-05-36-53](https://cloud.githubusercontent.com/assets/14506/3731872/22fcfdac-16f3-11e4-83c4-724df5415adb.png)

Sometimes it's all lines, sometimes just 2-3 entries.

Nexus 5, Android 4.4.2, ART.

**Comment by monday8am** [comment]
out of date. The ListView has been replaced by a RecyclerView. There are not overflow-fades in the currret cells.
