### ISSUE TITLE
Time entry stop action is reverted

### ISSUE THREAD

**Issue by roosmaa** [toggl/mobile#308]
A user reported the following (in Android 7.0.15):

> When i click stop, it stops timing for maybe 5 seconds (the red stop turns to a green start), then it starts counting again (from whatever time it stopped at). It happens ~50% of the time.

The delay between stopping and restarting is most likely due to the time it takes to sync with the server. Although is is not clear (nor do I have any ideas) what could cause the local stopped state to be overwritten by the server state before it is sent to the server.

Desk#84642

**Comment by taavirehemagi** [comment]
old issue, no longer relevant
