### ISSUE TITLE
Infinite syncing and login failure

### ISSUE THREAD

**Issue by roosmaa** [toggl/mobile#314]
With Android 7.0.15 a user is describing that they are seeing the buggy behaviour (#305, #303) which was main problem of 7.0.14 (and should've been fixed!).

> 1. I log into Toggl on my Android 4.3 phone, start entering time.
> 2. A few hours later I log into Toggl on a Windows 7 desktop via the Chrome
> browser and also start entering time.
> 3. At this point both the Chrome and Android app time entries are all
> perfectly synced and all is good.
> 4. I start entering more time entries on my phone. These entries are not
> showing up in Chrome on my Win7 machine.
> 5. I notice the Android app is stuck in a "syncing..." status and will not
> resync. Note that network connectivity is fine on the phone and all other
> Internet based apps are working fine.
> 6. I put the phone in and then out of airplane mode in an attempt to
> restart the sync process. This forces the Toggl app to retry syncing but
> it still never completes getting stuck at "Syncing..."
> 7. I logout of the Android app and attempt to log back in with my email /
> password. I get "invalid username or password". I then enter the exact
> same credentials into Win7/Chrome and it logs me right into the Toggl
> website.
> 8. After logging into Toggl on Chrome none of the entries I inputted on my
> phone are there.

The way the user was able to log back in was to reboot their phone.

This was the exact behaviour that reusing (and corrupting) the HttpClient resulted in, but which was fixed in 7.0.15. Problem is there aren't any errors in Bugsnag related to this user nor anything else to go on.

It seems we need better diagnostic tools in the app. First off by sending logs to us with the feedback view #311.

Desk#84501

**Comment by taavirehemagi** [comment]
not relevant any more
