### ISSUE TITLE
LastRun timestamp can resurrect

### ISSUE THREAD

**Issue by roosmaa** [toggl/mobile#324]
When the sync is running (due to bad connectivity) and when the user logs out during that time, the LastRun is [set to null](https://github.com/toggl/mobile/blob/ad2e7c3e46bb1305db500d670f582889ca02b22a/Phoebe/Net/SyncManager.cs#L46) for as long as the sync finishes running, then the previous value [is restored](https://github.com/toggl/mobile/blob/ad2e7c3e46bb1305db500d670f582889ca02b22a/Phoebe/Net/SyncManager.cs#L77). After that the next login attempt will fail to get users full dataset.

**Comment by monday8am** [comment]
out of date.
