### ISSUE TITLE
Update draft tags when mobile tag setting changes

### ISSUE THREAD

**Issue by roosmaa** [toggl/mobile#332]
Currently on Android we use draft time entry for creating new entries. When the "mobile" tag setting is toggled, the draft remains with the tag. It would be nice to have the mobile tag be automatically removed from it.

**Comment by monday8am** [comment]
In other words, "disabling automatic "mobile" tag doesn't really disable it"

**Comment by monday8am** [comment]
fixed at https://github.com/toggl/mobile/commit/6e86402eede2bdb67ce6e6f255b0c562be857715
