### ISSUE TITLE
Check issue related with request when zoom level is changed in Reports

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#465]
In Android, every time the zoom level is changed,  a Toggl.Phoebe.Net.UnsuccessfulRequestException: 400 (Bad Request)) is generated.

**Comment by monday8am** [comment]
indeed, if you assign a new adapter (MainPagerAdapter) to the viewPager, if is the first time, everything works ok. But if a previous adapter exists (when you change zoom level), the viewPager try to create two early fragments at positions 0 and 1, in this moment a wrong call to server is produced.

Once you set the correct position, the viewPager re-create new fragments with the correct positions and everything works good. I think is not a major issue but with a time-consuming solution. Currently everything works ok and the wrong call is correctly managed.

**Comment by roosmaa** [comment]
Yeah, not a high priority. Probably should label this issue as wontfix? :smiling_imp:

**Comment by monday8am** [comment]
:D .. is a good and pragmatic solution ;)  
We could "teach" to SummaryView to avoid requests with impossible dates, but will be the same behaviour than generate an exception. And is the server who really knows if a date is wrong or not.

I could investigate more about the Adapter property but I should browse android code this time :)
