### ISSUE TITLE
Reports should display data across all user workspaces

### ISSUE THREAD

**Issue by roosmaa** [toggl/mobile#468]
Currently reports only display data from user default workspace, which is OK for most users. However, for people who actually use several workspaces - this is bad.

Reports should really display information across all workspaces the user has tracked time into and has access to.

**Comment by pmgower** [comment]
Is this still a planned feature?  I would really like to ability to see my full week across all workspaces to get an idea of how many hours I worked for the week.

**Comment by monday8am** [comment]
@pmgower, yes, this feature is in our roadmap for the next *weeks*

**Comment by monday8am** [comment]
closed by #1750
