### ISSUE TITLE
Workaround related with SSL certificates in Xamarin

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#499]
Maybe related with that:
https://forums.xamarin.com/discussion/2923/ssl-connect-exception-the-authentication-or-decryption-has-failed

**Comment by monday8am** [comment]
hi @webervin, still we have problems with the SSL conf. and the iOS app?

**Comment by webervin** [comment]
that one needs testing to be answered, do you want me to setup some "secure
nginx" so you can try ?

**Comment by monday8am** [comment]
@webervin I don't know. Are you (the services) already working with the correct security level?

**Comment by webervin** [comment]
nope, we have reduced (compared to modern levels) security settings live.

**Comment by monday8am** [comment]
seems to be fixed with the use of ModernHttpClient. #1534 #1542
