### ISSUE TITLE
Optimize for iPad

### ISSUE THREAD

**Issue by FlourishFlora** [toggl/mobile#558]
Currently Toggl is only available for iPhone. While you can install iPhone apps on iPad, it's not as good as a native iPad app.

I don't know much about how Xamarin works. How hard would it be to port it to iPad?

**Comment by monday8am** [comment]
@FlourishFlora iPad is not included in our current roadmap. Tablets will be covered by the *responsive* version of the web client. I'll close this issue. Thanks for your feedback!
