### ISSUE TITLE
Port to Windows Metro

### ISSUE THREAD

**Issue by FlourishFlora** [toggl/mobile#559]
It would be cool if Toggl were available for Windows (Phone) 8.1. There are some unofficial timers on the Windows Phone Store, but they're not as elegant or feature-packed as the official mobile apps.

**Comment by monday8am** [comment]
@FlourishFlora, We're using a MvvM architecture in our code base and standard libraries and procedures to facilitate a *port* process of our code to a windows phone app, but an "in-house" client is not in our roadmap.
