### ISSUE TITLE
Month data (only January?) is not included when generating annual reports

### ISSUE THREAD

**Issue by masterrr** [toggl/mobile#600]
![screenshot_2015-04-15-09-46-41_resized](https://cloud.githubusercontent.com/assets/720966/7214626/2fb71f70-e5bd-11e4-9f7c-cb0715677185.png)
![screenshot_2015-04-15-09-46-50_resized](https://cloud.githubusercontent.com/assets/720966/7214627/3037dcfa-e5bd-11e4-9e5c-3e8d9075ea75.png)

**Comment by monday8am** [comment]
it is currently working. Bug related with data and not with reports exactly.
