### ISSUE TITLE
Start/Stop button appears in other fragments besides home.

### ISSUE THREAD

**Issue by taavirehemagi** [toggl/mobile#611]
Make it disappear when navigated to Feedback or Settings page.

**Comment by monday8am** [comment]
closed by #618

**Comment by monday8am** [comment]
@taavirehemagi if you start a TE the time label is visible in other screens. Please, check all implementation ( I think Start - Stop time disappeared for a while but I can't reproduce it)

**Comment by taavirehemagi** [comment]
Umm, when the timer is running, the duration should show everywhere in the app. Shouldn't it?

**Comment by monday8am** [comment]
ok. something more that we have to ask.

**Comment by monday8am** [comment]
Keep hidden for the moment (like previous version), later we can gather more opinions.
