### ISSUE TITLE
Overlap of time entry description with the numbers.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#616]
Try to check previous solution.

**Comment by taavirehemagi** [comment]
![screen shot 2015-04-28 at 15 50 43](https://cloud.githubusercontent.com/assets/2154171/7369893/5fc31aee-edbe-11e4-8910-c334ba914a3f.png)

Not sure if it looks better this way.

**Comment by monday8am** [comment]
:D 

- Decrease top and bottom margins
- in first line, put:  Client * Project   ______   Icons $ 2.00 h
- in second line, only description.
- Move the play button a bit to right, the same distance as previous version (edited)

**Comment by taavirehemagi** [comment]
:D aaalright

**Comment by monday8am** [comment]
Maybe this image can help you. Compare previous version and new. In new cells we have more space and smaller text! 
![slice1](https://cloud.githubusercontent.com/assets/1842773/7381809/f18ee5e0-ee07-11e4-80ca-34945c997317.png)

**Comment by monday8am** [comment]
@pe0ny Please, if you have time, give us your opinion here.

**Comment by taavirehemagi** [comment]
![screen shot 2015-04-30 at 11 33 02](https://cloud.githubusercontent.com/assets/2154171/7409167/c44da56e-ef2c-11e4-9986-a242f90e0c72.png)

**Comment by taavirehemagi** [comment]
Opinions? :dancer:

**Comment by pe0ny** [comment]
![f18ee5e0-ee07-11e4-80ca-34945c997317](https://cloud.githubusercontent.com/assets/5064445/7449917/7512e694-f247-11e4-85e7-185c2860dada.png)
right one is better. duration should definitely be aligned vertically center.

**Comment by monday8am** [comment]
thanks @pe0ny 
I don't have problems with the duration align. We only need a solution for this:

![screenshot_2015-04-27-19-39-42](https://cloud.githubusercontent.com/assets/1842773/7450196/6507a0d2-f242-11e4-9015-c971fa1015e3.png)

When you have Client info, tags and billable info the space is not enough and the text is small. Please, let us know your solution.

**Comment by pe0ny** [comment]
Let's try to align TE texts and resume button 16dp from left and right (so we'll get 32dp extra space).

![android-material-1](https://cloud.githubusercontent.com/assets/5064445/7453768/7c3c7baa-f275-11e4-89eb-3f1819f81107.png)

**Comment by monday8am** [comment]
closed by #658
