### ISSUE TITLE
Edit TE: Fix alignment (tags, start/end entries)

### ISSUE THREAD

**Issue by masterrr** [toggl/mobile#626]

**Comment by masterrr** [comment]
Should I work on this issue? Discussion / point is overlapping with https://github.com/toggl/mobile/issues/631

**Comment by monday8am** [comment]
@masterrr you don't need to wait. Check the current state of app and you'll notice elements without the correct alignment.

**Comment by masterrr** [comment]
Closed by https://github.com/toggl/mobile/pull/660
