### ISSUE TITLE
Edit TE: Fix colors (green tones of start button and tags backgrounds)

### ISSUE THREAD

**Issue by masterrr** [toggl/mobile#627]

**Comment by monday8am** [comment]
@pe0ny here we need your advice. There are two tones of green ( the tag bg and start button bg) and are different. Should we use both or pick only one? For the start button we have used the green color from previous version.

**Comment by pe0ny** [comment]
We should use only one color: #4dd965

**Comment by masterrr** [comment]
@monday8am tags view uses the right version of color (material_green). Closing the issue?

**Comment by masterrr** [comment]
Closed by https://github.com/toggl/mobile/pull/662
