### ISSUE TITLE
Edit TE: Fix shadow inconsistency

### ISSUE THREAD

**Issue by masterrr** [toggl/mobile#628]

**Comment by monday8am** [comment]
@pe0ny Our question here simple: 
The app is flat except in the screen related with Group edition. In my experience, the app should keep the same UI language in all screens, the shadow defines a new elevation (like a new floor), if you use two steps or elevations in one screen to separate a content at top (action bar) from content at bottom (list of items), you should keep this line for the rest of the screens. 

Resuming, the app should be entirely flat, or use two levels every time we need a list flowing under a bar. Let me know what you think.

![screen shot 2015-04-28 at 12 16 15](https://cloud.githubusercontent.com/assets/1842773/7373289/ca016d04-edcb-11e4-9fdd-e767c7e60773.png)

**Comment by pe0ny** [comment]
I agree about consistency but the app isn't and shouldn't be entirely flat.

Elements with shadows are:
* Toolbar
* Time entries 
* Floating buttons
* Opened navigation drawer
* Edit TE form when editing multiple TE and then also other TE in the list

![shadow-1](https://cloud.githubusercontent.com/assets/5064445/7488795/a589024a-f3d7-11e4-8a69-9f58dc5db60f.png)
![shadow-2](https://cloud.githubusercontent.com/assets/5064445/7488797/aa774488-f3d7-11e4-9d86-40065d6a3554.png)
![shadow-3](https://cloud.githubusercontent.com/assets/5064445/7488799/adf72aba-f3d7-11e4-915f-cdfbe5d60bd7.png)

These rely on material design guidlines. In material design the physical properties of paper are translated to the screen. Background of the app is flat but elements on it are separate from the app content.

![material](https://cloud.githubusercontent.com/assets/5064445/7488779/76e80a3a-f3d7-11e4-82b1-3de06dc4095e.png)

All these principles are well explained here:
http://www.google.com/design/spec/layout/principles.html#principles-how-paper-works
http://www.google.com/design/spec/what-is-material/material-properties.html#

**Comment by monday8am** [comment]
nice snapshots! Thanks @pe0ny we'll try to follow them.

**Comment by monday8am** [comment]
@masterrr please, removed the planned tag.

**Comment by pe0ny** [comment]
toolbars with shadow:

![bgtoolbar](https://cloud.githubusercontent.com/assets/5064445/7681866/46ec2b78-fd7c-11e4-8284-dff893cfd99e.png)

![bgtoolbar](https://cloud.githubusercontent.com/assets/5064445/7681869/4b48bbd2-fd7c-11e4-839f-895eb8315513.png)

![bgtoolbar](https://cloud.githubusercontent.com/assets/5064445/7681872/4ff60324-fd7c-11e4-962e-0ed6962979dc.png)

![bgtoolbar](https://cloud.githubusercontent.com/assets/5064445/7681875/5462f2e6-fd7c-11e4-968c-69e0524f62f6.png)

**Comment by masterrr** [comment]
@pe0ny thanks!

**Comment by masterrr** [comment]
Closed by https://github.com/toggl/mobile/pull/673
