### ISSUE TITLE
Runtime error in EditTimeEntryTagsBit.cs

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#632]
[mono-rt]   at (wrapper managed-to-native) object.wrapper_native_0xb4dc9a00 (intptr,intptr,intptr,Android.Runtime.JValue*) <IL 0x0002e, 0xffffffff>
[mono-rt]   at Android.Runtime.JNIEnv.CallVoidMethod (intptr,intptr,Android.Runtime.JValue*) [0x00040] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:567
[mono-rt]   at Android.Widget.TextView.set_TextFormatted (Java.Lang.ICharSequence) [0x0004b] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/platforms/android-18/src/generated/Android.Widget.TextView.cs:2700
[mono-rt]   at Android.Widget.TextView.set_Text (string) [0x00013] in /Users/builder/data/lanes/monodroid-mavericks-monodroid-5.1-series/d23da369/source/monodroid/src/Mono.Android/platforms/android-18/src/generated/Android.Widget.TextView.cs:2711
[mono-rt]   at Toggl.Joey.UI.Views.EditTimeEntryTagsBit.RebindTags (Toggl.Phoebe.Data.Views.TimeEntryTagsView) [0x0002c] in /Users/anton/Projects/mobile/Joey/UI/Views/EditTimeEntryTagsBit.cs:74
[mono-rt]   at Toggl.Joey.UI.Fragments.BaseEditTimeEntryFragment.RebindTags () [0x0001e] in /Users/anton/Projects/mobile/Joey/UI/Fragments/BaseEditTimeEntryFragment.cs:261
[mono-rt]   at Toggl.Joey.UI.Fragments.BaseEditTimeEntryFragment.OnTimeEntryTagsUpdated (object,System.EventArgs) [0x00002] in /Users/anton/Projects/mobile/Joey/UI/Fragments/BaseEditTimeEntryFragment.cs:253
[mono-rt]   at Toggl.Phoebe.Data.Views.TimeEntryTagsView.OnUpdated () [0x0006b] in /Users/anton/Projects/mobile/Phoebe/Data/Views/TimeEntryTagsView.cs:45
[mono-rt]   at Toggl.Phoebe.Data.Views.TimeEntryTagsView.OnDataChange (Toggl.Phoebe.Data.DataObjects.TimeEntryTagData,Toggl.Phoebe.Data.DataAction) [0x00103] in /Users/anton/Projects/mobile/Phoebe/Data/Views/TimeEntryTagsView.cs:103
[mono-rt]   at Toggl.Phoebe.Data.Views.TimeEntryTagsView.OnDataChange (Toggl.Phoebe.Data.DataChangeMessage) [0x00052] in /Users/anton/Projects/mobile/Phoebe/Data/Views/TimeEntryTagsView.cs:54

**Comment by monday8am** [comment]
fixed at #665

**Comment by masterrr** [comment]
Closed by https://github.com/toggl/mobile/pull/669
