### ISSUE TITLE
Swiping down for "Load more" will make app unresponsive

### ISSUE THREAD

**Issue by kristerhaav** [toggl/mobile#637]
Just swipe down until you hit the end of the list. It might work at first but soon enough I get the "The app has become unresponsive" dialog.

**Comment by masterrr** [comment]
Stacktrace https://gist.github.com/masterrr/f36ca5ed4400147c5417

**Comment by masterrr** [comment]
@kristerhaav does it happen only when having huge (50+ entries) amount of entries? Or small amounts (1–50) produce the same bug for you? 

Seems like a memory GC issue (leak?)

**Comment by taavirehemagi** [comment]
@masterrr How were you able to reproduce this? I haven't been able to.

**Comment by monday8am** [comment]
fixed at https://github.com/toggl/mobile/commit/aa5209fd90cfe7ea93e64d683d7efc6d6202d3e5
