### ISSUE TITLE
Set a new Splash view

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#640]
Splash view isn't showed.

**Comment by pe0ny** [comment]
Splash screen:

![toggl-splashscreen](https://cloud.githubusercontent.com/assets/5064445/7680065/780350a8-fd6b-11e4-843c-cd907074e9b3.png)

**Comment by monday8am** [comment]
nice! :+1:

**Comment by pe0ny** [comment]
Use "bgArrowsFull.png" and "logo.png" from assets folder:
https://drive.google.com/a/toggl.com/folderview?id=0B3HI5pCjbfU2VS01aDNROVZ5SlE&usp=sharing

**Comment by taavirehemagi** [comment]
:+1:

**Comment by pe0ny** [comment]
![bgsplash](https://cloud.githubusercontent.com/assets/5064445/7698445/02d95198-fe19-11e4-8b42-dc0af88365f3.png)
![bgsplash](https://cloud.githubusercontent.com/assets/5064445/7698450/09714a74-fe19-11e4-9873-23a3eace95a8.png)
![bgsplash](https://cloud.githubusercontent.com/assets/5064445/7698458/0e1beafc-fe19-11e4-9eb7-771bb90441ae.png)
![bgsplash](https://cloud.githubusercontent.com/assets/5064445/7698460/16fe9c64-fe19-11e4-9f4d-15051bdb8862.png)
![bgsplash](https://cloud.githubusercontent.com/assets/5064445/7698459/113bb9ce-fe19-11e4-9061-2c506f49bd17.png)

**Comment by taavirehemagi** [comment]
Closed by #682
