### ISSUE TITLE
Placeholder activation.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#654]
For some reason is description placeholder always red. Placeholders and lines should be coloured red only if field is active (eg user typing something)

**Comment by masterrr** [comment]
@monday8am please test if the issue is still active on your device

**Comment by monday8am** [comment]
@masterrr you didn't tested it?

**Comment by masterrr** [comment]
@monday8am fully tested on Nexus 5 & emulator, I remember you had different kind of the issue

**Comment by monday8am** [comment]
@masterrr for me works ok :+1:

**Comment by masterrr** [comment]
Fixed by https://github.com/toggl/mobile/issues/666
