### ISSUE TITLE
Background and height of Toolbar

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#655]
What is the toolbar height atm? can we try to increase it to 56dp?
And can we use background image instead of background color?

**Comment by monday8am** [comment]
@pe0ny We´re using the standard size (actionBarSize value) and think it´s 56dp in all places.
> And can we use background image instead of background color?
Could you let me know the screen?

**Comment by pe0ny** [comment]
It's ok. Then it just seemed smaller. :)

On mobile screen it was plain grey:
![screenshot_2015-05-04-15-54-11](https://cloud.githubusercontent.com/assets/5064445/7453891/9614f196-f276-11e4-9961-0ed1eea7f967.png)
But on desktop screen I saw the difference. Can we try with this background (a bit darker):
![bgarrows2](https://cloud.githubusercontent.com/assets/5064445/7453950/46a2ffb2-f277-11e4-89ac-7b750c8076f2.png)

**Comment by monday8am** [comment]
sure! :+1:

**Comment by monday8am** [comment]
sure! :+1: I think the problem is in the triangle vortices distribution.
only for toolBar? (the bg is used in leftside panel)  If you want to use a different image just give me a bg in this 4 sizes:
360x60
540x90
720x120
1080x180

**Comment by pe0ny** [comment]
Yes, it's only for the toolbar.

1080x180:
![bgarrows2](https://cloud.githubusercontent.com/assets/5064445/7468128/4946f1c4-f30d-11e4-9628-53a39cfce28c.png)

720x120:
![bgarrows2](https://cloud.githubusercontent.com/assets/5064445/7468140/5f6e6e5a-f30d-11e4-9cba-af9244aa82e3.png)

540x90:
![bgarrows2](https://cloud.githubusercontent.com/assets/5064445/7468144/729fd00e-f30d-11e4-9f97-b5644178d076.png)

360x60:
![bgarrows2](https://cloud.githubusercontent.com/assets/5064445/7468149/87d230c0-f30d-11e4-9bfe-58872cee4616.png)

**Comment by monday8am** [comment]
:+1: thanks!

**Comment by monday8am** [comment]
closed by #657
