### ISSUE TITLE
Login button background. 

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#661]
@pe0ny We'll need this images with the correct green color:

https://github.com/toggl/mobile/blob/master/Joey/Resources/drawable-mdpi/ButtonGreenDefault.9.png
https://github.com/toggl/mobile/blob/master/Joey/Resources/drawable-mdpi/ButtonGreenPressed.9.png

https://github.com/toggl/mobile/blob/master/Joey/Resources/drawable-hdpi/ButtonGreenDefault.9.png
https://github.com/toggl/mobile/blob/master/Joey/Resources/drawable-hdpi/ButtonGreenPressed.9.png

https://github.com/toggl/mobile/blob/master/Joey/Resources/drawable-xhdpi/ButtonGreenDefault.9.png
https://github.com/toggl/mobile/blob/master/Joey/Resources/drawable-xhdpi/ButtonGreenPressed.9.png

https://github.com/toggl/mobile/blob/master/Joey/Resources/drawable-xxhdpi/ButtonGreenDefault.9.png
https://github.com/toggl/mobile/blob/master/Joey/Resources/drawable-xxhdpi/ButtonGreenPressed.9.png

I know the login screen will change, but for the feedback screen.

**Comment by pe0ny** [comment]
Do we need images if we use flat (#4dd965) buttons (no border and without gradient)?

**Comment by masterrr** [comment]
@pe0ny if no borders, gradients, shadows and weird transformations then no need for images

**Comment by pe0ny** [comment]
ok. no weird stuff, just plain button. then I won't generate 9-patches.

**Comment by masterrr** [comment]
@monday8am we can remove these .pngs completely and use pure color codes

**Comment by monday8am** [comment]
@masterrr @pe0ny For me is the same, this screen should be replaced soon. I want the more simple and fast solution: replace one color in 8 pngs or replace the whole button with new code, using no more than 15 minutes of your  time.

**Comment by taavirehemagi** [comment]
#closed by #671
