### ISSUE TITLE
Start toolbar button disappears after switching to the another activity via drawer, then going back

### ISSUE THREAD

**Issue by masterrr** [toggl/mobile#672]

**Comment by monday8am** [comment]
maybe this is the normal behaviour:
https://github.com/toggl/mobile/issues/611

@masterrr to be sure, behaivor should be the same as production version

**Comment by masterrr** [comment]
@monday8am just checked out the app from the Google Play. The start button _appears_ if we are going back from the e.g. settings.

Though In our current android-redesign state the button doesn't come back (#611 is about switching off the button in other fragments, and yeah it's fixed), that's what this PR is about

**Comment by masterrr** [comment]
![settings_button_demo](https://cloud.githubusercontent.com/assets/720966/7667538/874cad8c-fc14-11e4-946e-e11d2a7519f2.gif)

**Comment by monday8am** [comment]
@masterrr :+1:

**Comment by masterrr** [comment]
Closed by https://github.com/toggl/mobile/pull/677
