### ISSUE TITLE
Correct alignment of items. Edit group screen.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#675]
fix alignment. Center correctly the time text and align items.
@pe0ny please, let us know your opinnion about correct alignment.  

![nexus 4 kitkat screentshot 1](https://cloud.githubusercontent.com/assets/1842773/7678881/0aad4800-fd58-11e4-8f42-7409eb340684.png)

**Comment by pe0ny** [comment]
Correct margins:
* Back icon 16dp from left
* Edit fields 32dp from left and right (seem correct atm)
* "End" should start from center
* Other TE - clock icon should be 32dp from left, also duration 32dp from right

![keylines-4](https://cloud.githubusercontent.com/assets/5064445/7679727/3f1426da-fd68-11e4-90fc-d3ed530eda7b.png)
![keylines-5](https://cloud.githubusercontent.com/assets/5064445/7679767/9db2799e-fd68-11e4-8afe-b6fc6bbbcc3b.png)

**Comment by monday8am** [comment]
@pe0ny  thanks! :+1:

**Comment by taavirehemagi** [comment]
Closed by #683
