### ISSUE TITLE
Fix background size for TE screen.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#690]
Center background to use only the space assigned (like toolbar bg)

**Comment by masterrr** [comment]
I'm using the second mode from the left, CENTER_CROP.
![04fig09_alt](https://cloud.githubusercontent.com/assets/720966/7736155/a3546252-ff4a-11e4-82e7-fbd5f1898b1c.jpeg)

**Comment by masterrr** [comment]
Is the point of this issue to eliminate the scrollbar from the single TE? @monday8am

**Comment by masterrr** [comment]
Closed by https://github.com/toggl/mobile/pull/703
