### ISSUE TITLE
Reports sometimes shows a wrong number.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#708]
Ask to server team about this possible error.

![wrong_numbers](https://cloud.githubusercontent.com/assets/1842773/7767111/1584f258-0070-11e5-832f-2b90b903dff9.png)

**Comment by masterrr** [comment]
![toggl_report_ipad_strange](https://cloud.githubusercontent.com/assets/720966/8795255/1d12913a-2f94-11e5-9e60-6d3cc8aad7dc.png)

**Comment by monday8am** [comment]
seems to be it is fixed by https://github.com/toggl/mobile/pull/1038
