### ISSUE TITLE
Signup screen

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobile#719]
![toggl-android-signup-active-fields](https://cloud.githubusercontent.com/assets/5064445/7809135/d2d44740-03a0-11e5-9c74-11b70cdc1a61.png)

Active fields: 
* Active line - #f30c16 70%
* Active type - #f30c16 50%

Disclaimer: Roboto Regular (links Roboto Bold) 12sp #f5f5f5

Disabled button (#3b3b3b):
![toggl-android-signup-disabled-btn](https://cloud.githubusercontent.com/assets/5064445/7809174/18a4477a-03a1-11e5-9947-c025e9b41f62.png)

**Comment by taavirehemagi** [comment]
Closed in #744
