### ISSUE TITLE
Add task items to project list 

### ISSUE THREAD

**Issue by taavirehemagi** [toggl/mobile#755]
- [x] Show tasks on list
- [x] make task item clickable
- [x] make project row expand and collapse task items
- [x] implement material design to task list item

![toggl-android-projects](https://cloud.githubusercontent.com/assets/2154171/7984998/1953a256-0ad6-11e5-98fe-32ba51f94bff.png)

**Comment by masterrr** [comment]
Closed by https://github.com/toggl/mobile/pull/761
