### ISSUE TITLE
Investigate bug related with PR #764

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#772]
The bug is fixed but we should know why the data isn't correct.

**Comment by masterrr** [comment]
I investigated this while fixing the bug https://github.com/toggl/mobile/pull/764
I couldn't find any meaningful reason of why it happens. 

EditTimeEntryFragment takes one param in the constructor: TimeEntryData entity. The Fragment is being instantiated from the Activity. The TimeEntryData should come to Activity from the intent, but rarely  it doesn't.

I can't reproduce intent extra = null both on devices & simulators so I force-simulated extra = null in code, gives me the exact same error. And I fixed it.

**Comment by masterrr** [comment]
The last possible “reason” can be this, very similar issue http://stackoverflow.com/a/18154106/1279330 and we do it the wrong way, if projecting our solution

**Comment by masterrr** [comment]
@monday8am I can try SO advice and we'll see if the issue persists

**Comment by masterrr** [comment]
Goes pending via https://github.com/toggl/mobile/pull/793

**Comment by monday8am** [comment]
fixed.
