### ISSUE TITLE
Navigational transitions: TE List

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobile#787]
From TE List to detail view:

![anim](https://cloud.githubusercontent.com/assets/5064445/8183548/873ab24a-1441-11e5-9767-fb165aace476.png)

From list to detail we should use navigational transition like this: http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsWjgyVU9kMWN0V2s/patterns_navigational-transitions_parent-to-child_list-02_xhdpi_019.webm The surface that the user touches (list element) should lift up and expand into place from its origin.

**Comment by monday8am** [comment]
@pe0ny good example! Please, if is possible and you have time, include another issue for login screen transition.

**Comment by taavirehemagi** [comment]
Closed by 0459c5924765f346f3a1be8bcfa0af6c6fbeaf66
