### ISSUE TITLE
Floating button animation

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobile#790]
![toggl-fab](https://cloud.githubusercontent.com/assets/5064445/8205003/69b6bb24-14f5-11e5-936e-90fc30f07f0f.gif)

Video with better quality in drive: https://drive.google.com/a/toggl.com/file/d/0B3HI5pCjbfU2SHBhZ1VzLUVmczA/view?usp=sharing

**Comment by monday8am** [comment]
open - close animation was implemented.
