### ISSUE TITLE
Application remain over lock screen

### ISSUE THREAD

**Issue by cosic** [toggl/mobile#792]
Case:
1. Start application
2. Lock device
3. Unlock device (Showed previous activity of application instead of common lock screen)
4. Select item (After that showed common lock screen)
5. Unlock device (Passes to next activity after click by item)

Maybe [this](https://github.com/LiveTyping/u2020-mvp/issues/6) will help solve the problem.

**Comment by monday8am** [comment]
fixed in previous versions.
