### ISSUE TITLE
Google + login should open in an internal browser.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#809]
Comments from Apple reviewer:

*It will be necessary to allow users to login with Google in the app, such as in a web view, for example.*

and:

*We noticed an issue in your app that contributes to a lower quality user experience than Apple users expect. Specifically, upon launching the app, a web page in mobile Safari opens for Google log-in, then returns the user to the app. The user should be able to log in without opening Safari first.*

**Comment by masterrr** [comment]
Closed by https://github.com/toggl/mobile/issues/824
