### ISSUE TITLE
New copy for Google Play Store

### ISSUE THREAD

**Issue by annikatoggl** [toggl/mobile#830]
Log your work time in teams or personal activities as a single user. Toggl is the leading cloud based time tracking tool for accurate and transparent client billing, for simple employee time management or for increasing personal productivity. Check out your time usage reports inside the app or export complete timesheets from the web version. 
Toggl time recording app features:
✓ Log your time both online and offline
✓ Set up projects, clients, tasks and tags
✓ Real time sync between app and web version
✓ Export reports & timesheets from the web app (www.toggl.com)
✓ Mark time logs as billable* or non-billable.
✓ Free collaborative time tracking account  for teams of up to 5 members
Detailed time record reports of how you or your team have spent their time can be generated from the web app and also shared via special link to others. 

* Pro account feature. You can upgrade from the web app.

**Comment by monday8am** [comment]
done!
