### ISSUE TITLE
The start button is half out of the screen and cannot be clicked

### ISSUE THREAD

**Issue by gabor-farkas** [toggl/mobile#860]
LG-D855, Android 5.0 V20h-EUR-XX
![toggle android](https://cloud.githubusercontent.com/assets/2929085/9060488/bb3fd2ac-3ab4-11e5-9951-ed507ffe47d2.png)

**Comment by monday8am** [comment]
thanks @gabor-farkas! 
we'll push the solution in an hour or so.

**Comment by gabor-farkas** [comment]
Wow that was quick thanks!
