### ISSUE TITLE
New copy for App Store

### ISSUE THREAD

**Issue by annikatoggl** [toggl/mobile#863]
Title: Toggl Time Tracker
Copy:
Log your work time in teams or personal activities as a solo user. Toggl is the most popular cloud based time tracking tool for accurate and transparent client billing, simple employee time management or for increasing personal productivity. Check out your time usage reports inside the app or export complete timesheets from the web version. 
Toggl time recording app features:
✓ Log your time both online and offline
✓ Set up projects, clients, tasks and tags
✓ Real time sync between app and web version
✓ Export reports & timesheet from the web app (www.toggl.com)
✓ Mark time logs as billable* or non-billable.
✓ Free collaborative time tracking account  for teams of up to 5 members
Detailed time record reports of how you or your team have spent their time can be generated from the web app and also shared via special link to others. 

* Pro account feature. You can upgrade from the web app.

PS: if there's an option to add keywords too, let me know!

**Comment by monday8am** [comment]
*Pro account feature. You can upgrade from the web app.*
*Export reports & timesheet from the web app (www.toggl.com)*

the new release was rejected 5 days ago exactly because this two lines :dancers: :P 
Apple don't let to put info about to buy something. You have to use their mechanism to buy your app.

**Comment by annikatoggl** [comment]
oh no, remove the lines then :)

**Comment by monday8am** [comment]
ready.
