### ISSUE TITLE
Make empty state for workspaces that have no projects

### ISSUE THREAD

**Issue by taavirehemagi** [toggl/mobile#871]
Must have an empty state for ViewPager
Epic #864

**Comment by taavirehemagi** [comment]
Empty workspaces contain a "No project" row and are never empty. Maybe should have an OBM message saying click on the FAB to create your first project.
![image](https://cloud.githubusercontent.com/assets/2154171/9323518/0c531796-458a-11e5-8116-f30d92444ef7.png)

**Comment by pe0ny** [comment]
![toggl-android-projects-emptystate](https://cloud.githubusercontent.com/assets/5064445/9355843/5177e666-4685-11e5-9f7c-9ad2342597e2.png)

Assets (arrow and little Toggler): https://drive.google.com/a/toggl.com/folderview?id=0B3HI5pCjbfU2VS01aDNROVZ5SlE&usp=sharing

"You haven't created any projects in this workspace yet. Create one now!" - Roboto Light & Regular 16sp #4e4e4e
Red FAB #f30c16

**Comment by taavirehemagi** [comment]
Closed by 4cfb948bc72605af2b25e4a500873dc53b8a9b19
