### ISSUE TITLE
Improve readability of Timer list 

### ISSUE THREAD

**Issue by jalton** [toggl/mobile#883]
It's difficult to view descriptive text for entries, both on the Timer list screen and in the entry details screen. Most of the descriptive text for my entries disappears beneath the time column. 

I would appreciate some way to view all (or at least more) of an entry's descriptive text, either on the Timer view screen or the entry details screen (maybe wrap the text) in the iOS app. 

Thanks for listening. 

![toggl_descriptivetext](https://cloud.githubusercontent.com/assets/1235107/9342526/d589f602-45c1-11e5-9d6e-846bdac42c88.jpeg)

**Comment by monday8am** [comment]
thanks for reach out @jalton 
We have discussed this topic many times and we're working in a solution for the next weeks. Our solution pass for different heights for the items with three or two lines. I have linked this issue with the original issue.
