### ISSUE TITLE
Multiple active timers?

### ISSUE THREAD

**Issue by JoshMcCullough** [toggl/mobile#885]
Is there any way to have more than one timer running at a time for a single user? An example case would be if I was doing work while also listening to training, I would have a timer running for the work and a timer running for training so I could keep track of how much time I spent training (while also working or not).

**Comment by monday8am** [comment]
Hi Josh!
thanks for reach out. This is not possible right now and is against to our concept of productivity ;) 
http://blog.toggl.com/2015/02/how-to-stop-multitasking/

In any case, we should implement it in the API and then in the mobile app.

**Comment by JoshMcCullough** [comment]
Understood, thanks!

**Comment by monday8am** [comment]
:+1:
