### ISSUE TITLE
User's first steps after sign up

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobile#930]
1. Describe your activity
![toggl-android-tip-vol3-1](https://cloud.githubusercontent.com/assets/5064445/9763593/b7c79f7a-570a-11e5-8efc-eb76958ee35f.png)

2. Start tracking
![toggl-android-tip-vol3-2](https://cloud.githubusercontent.com/assets/5064445/9763600/c00aef16-570a-11e5-9749-d56a18db0ec8.png)

3. Activity
![toggl-android-tip-vol3-3](https://cloud.githubusercontent.com/assets/5064445/9763603/c7c65196-570a-11e5-8f64-a76cad5b8038.png)

**Comment by pe0ny** [comment]
Assets: https://drive.google.com/a/toggl.com/folderview?id=0B3HI5pCjbfU2VS01aDNROVZ5SlE&usp=sharing

Overlay: #f5f5f5 76%

Texts: Roboto Light 24sp #303030

Button:
* Roboto Medium 14sp #ffffff 
* 78x46dp (step 2 and 3: 104x46dp) and  background #4dd965

Circles: 8dp #4dd965 40% (active 100% opacity)

**Comment by monday8am** [comment]
great job @pe0ny. We'll use this issue as root for further issues related with OBM.

**Comment by monday8am** [comment]
@kyllikekimmel please, evaluate what we can use from this old issue. Is compatible with your current experiments?

**Comment by kyllikekimmel** [comment]
This was designed for a flow that isn't live now. Me and Heidi took the initial idea and created #1259.

**Comment by monday8am** [comment]
replaced by #1259
