### ISSUE TITLE
Modify swipe behavior in android

### ISSUE THREAD

**Issue by taavirehemagi** [toggl/mobile#954]
Right now the delete is too simple and happens accidentally. Also, users don't always notice the undo option. Would be nice to follow this example and swipe it twice for delete.
<img width="336" alt="screen shot 2015-09-30 at 15 35 11" src="https://cloud.githubusercontent.com/assets/2154171/10192992/dceafb88-6788-11e5-89ba-9899c4f65f9d.png">

**Comment by monday8am** [comment]
@taavirehemagi an old request. I think is a one day task. Let me know what you think.
