### ISSUE TITLE
Users can't tap the last project.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#971]
Is not possible to tap the last project on Project List because the FAB. Check if it is related with the device's size.

![image](https://cloud.githubusercontent.com/assets/1842773/10633172/56f7b1c6-77e9-11e5-8397-fcafe4b53296.png)

**Comment by monday8am** [comment]
I see right now that the problem is with the Task icon. A fast solution could be to get some bottom space to the list.

**Comment by monday8am** [comment]
@taavirehemagi is this issue already fixed?

**Comment by taavirehemagi** [comment]
yeah, it's fixed
